FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --no-fund --no-audit
COPY . .
RUN npm run build

FROM panse-system-web:lan
COPY --from=build /app/dist /usr/share/nginx/html
