"""Reviewed business semantics, NOT executable workflow or runtime receipts.

Keep stable IDs. Sources are repository-relative metadata, never customer data.
Every edge describes a checkable contract rather than inferred import lineage.
"""
VERSION = '2026-09-22.1'
DOMAINS = [
    ('npd', '新品研发', '产品'), ('product', '商品与规格', '产品'),
    ('bom', '物料与BOM', '产品'), ('price', '定价与版本', '价格'),
    ('campaign', '渠道与活动', '运营'), ('order', '客户与订单导入', '订单'),
    ('quantity', '定制数量确认', '人工确认'), ('factory', '工厂与制单', '工厂'),
    ('purchase', '采购与配件', '采购'), ('stock', '库存与齐套', '仓库'),
    ('shipping', '物流与安装', '物流'), ('after', '售后与补发', '售后'),
    ('finance', '财务与对账', '财务'), ('settlement', '付款与经营', '财务'),
    ('marketing', '营销与反馈', '运营'), ('sync', '飞书与外部投影', '飞书'),
    ('automation', '自动化与异常', '程序'), ('governance', '权限与追溯', '维护'),
]


def source(path, anchor=''):
    return {'path': 'backend/app/' + path, 'anchor': anchor}


def node(id, label, domain, field, path, anchor='', note=''):
    return {'id': id, 'label': label, 'domain': domain, 'field': field,
            'sources': [source(path, anchor)], 'note': note}


NODES = [
    node('automation.order_owner','订单原批次运行者核验','automation','recover_order_receipt','services/agent_ingest_service.py','def recover_order_receipt','running文件不等于任务存活；同attempt核对运行者，未知或中断不盲重导，不改财务或已推单'),
    node('stock.finished','成品现货与规格选择','stock','ProductInventory.physical_qty / sku','services/product_stock_ledger_service.py','def _pick_stock_row','现存规格回退分支需核实；不能视为精确子SKU库存证明'),
    node('stock.ship_movement','母单发货扣成品现货','stock','ProductStockMovement reason=ship entity=order','services/product_stock_ledger_service.py','def record_shipment','当前入口读取母单product_code/sku/qty，不证明多子SKU均已扣库'),
    node('stock.restock','备货单到货入成品库','stock','FactoryOrder.source_order_id / qty','services/product_stock_ledger_service.py','def record_restock_receipt','客户单MTO不计入可售现货'),
    node('stock.reversal','成品库存冲正流水','stock','ProductStockMovement reason=reversal','services/product_stock_ledger_service.py','def reverse','冲正现存流水，不据关系图执行库存调整'),
    node('governance.approval','审批状态与执行器','governance','ApprovalRequest / _EXECUTORS','services/approval_service.py','def approve','approved状态不单独证明执行器存在及动作实际完成'),
    node('shipping.confirmed_month','人工确认发货月份','shipping','Order.customer_shipping_month','services/factory_shipping_confirmation_service.py','def apply_confirmed_months','仅既有两笔精确授权；月份不补造日期，不改变生产权限'),
    node('governance.relationships','业务影响检查清单','governance','review_changes / flow_review','services/business_relationship_service.py','def review_changes','只读维护工具，不增加报名和订单执行前置门'),
    node('governance.source_index','全程序静态引用索引','governance','source_index / dependency_review','services/business_relationship_index.py','def source_index','索引候选不等于业务语义已审查；发布快照与运行源码区分'),
    node('npd.project','研发项目与阶段','npd','NpdProject / NpdStageInstance','models/npd.py'),
    node('npd.gate','任务、检验及成本关口','npd','NpdTask / NpdInspectionItem / NpdCostGate','services/npd_service.py','def move_project'),
    node('npd.materialize','设计正式建档','npd','materialize_project','services/npd_service.py','def materialize_project'),
    node('product.identity','产品身份','product','Product.code','models/product.py','class Product'),
    node('product.sku','规格身份','product','PricingSku.sku_code / product_code','models/pricing.py','class PricingSku'),
    node('product.dimensions','精确规格尺寸','product','PricingSku.size_info / verified_dimensions','services/factory_production_evidence.py','def verified_dimensions','不以其他变体或产品默认图替代'),
    node('product.custom','定制变体','product','CustomVariant.dimension_overrides','models/custom_variant.py'),
    node('bom.material','物料单价','bom','Material.price','models/material.py'),
    node('bom.lines','BOM单位用量','bom','BomLine.qty_per_product','models/bom.py'),
    node('bom.drift','成本差异提醒','bom','check_sku / check_for_material','services/pricing_bom_sync_service.py','def check_sku','只核查和提示，不自动调售价'),
    node('price.current','日常/中促/大促价格','price','PricingSku.daily_price / mid_promo / big_promo','models/pricing.py'),
    node('price.version','历史价格版本','price','PricingVersion','services/pricing_version_service.py'),
    node('price.formula','定价公式','price','PricingFormula','models/pricing_formula.py'),
    node('campaign.mapping','淘宝商品SKU映射','campaign','TaobaoListing / SkuIdentity','models/taobao_listing.py'),
    node('campaign.window','精确活动窗口与计划','campaign','CampaignPlan','models/campaign.py'),
    node('campaign.files','模板与价格文件','campaign','campaign_workflow_service','services/campaign_workflow_service.py'),
    node('campaign.receipt','官方报名终态','campaign','CampaignSignup','models/campaign_signup.py','', '已成功/未知结果不重传；不把上传成功当报名成功'),
    node('order.file','原报表与批次','order','ImportedFile / ImportJob','models/import_file.py'),
    node('order.parent','母订单','order','Order.order_no','models/order.py','class Order('),
    node('order.child','全部导入子订单','order','OrderDetail.sub_order_no / source','models/order.py','class OrderDetail'),
    node('order.qty','原购买数量','order','OrderDetail.qty','models/order.py','class OrderDetail','原始交易事实，不能被成品数量覆盖'),
    node('order.refund','子单关闭与退款','order','OrderDetail.line_status / refund_status','services/order_line_delivery_service.py'),
    node('order.notes','备注及身份版本','order','Order.buyer_message / remark / seller_memo / production_note','services/factory_production_evidence.py','def _identity'),
    node('order.customer','客户和收货信息','order','Customer / Order.customer_address','models/customer.py'),
    node('quantity.card','数量询问卡','quantity','factory_quantity_request:<line_id>','services/factory_quantity_request_service.py','def request_quantity'),
    node('quantity.reply','真实回复与身份核验','quantity','handle_reply','services/factory_quantity_request_service.py','def handle_reply'),
    node('quantity.physical','确认成品数量','quantity','factory_quantity_confirmation.physical_qty','services/factory_production_evidence.py','def quantity_confirmation','身份或备注变化会使确认失效'),
    node('factory.sheet','正式制单事实与图片','factory','FactorySheet.qty / size_info / materials','services/factory_sheet.py','def build_for_order_line'),
    node('factory.receipt','精确子单图片回执','factory','OrderDetail.factory_delivery_state / factory_delivery_message_id','services/order_line_delivery_service.py'),
    node('factory.archive','不可变已发图片档案','factory','ImportedFile.row_summary.rendered_line','services/order_sheet_archive_service.py','def archive_sent_line_snapshot'),
    node('factory.void','原图作废与更正','factory','order_line_delivery_service','services/order_line_delivery_service.py'),
    node('factory.order','工厂采购/生产单据','factory','FactoryOrder','models/order.py','class FactoryOrder'),
    node('purchase.quote','询价与供应商决策','purchase','ProcurementTask','models/procurement.py'),
    node('purchase.parts','配件采购与到货','purchase','PartPurchase','models/order.py','class PartPurchase'),
    node('purchase.supplier','供应商资料与评分','purchase','Supplier / SupplierScore','models/supplier.py'),
    node('stock.lock','BOM物料占用','stock','InventoryLockLedger','services/inventory_lock_service.py','def lock_for_factory_order'),
    node('stock.consume','发货消耗与释放','stock','consume_for_shipment / release_factory_order_lock','services/inventory_lock_service.py','def consume_for_shipment'),
    node('stock.inbound','入库、退回、拆解','stock','inbound_part / return_in_product / disassemble_product_to_parts','services/inventory_lock_service.py','def inbound_part'),
    node('stock.balance','库存结余与台账','stock','Inventory / InventoryLockLedger','models/inventory.py'),
    node('shipping.tracking','实体物流轨迹','shipping','Shipment.entity_type / entity_id / tracking_no','models/shipment.py'),
    node('shipping.status','有条件的签收派生','shipping','_apply_derivation','services/shipment_service.py','def _apply_derivation'),
    node('shipping.fulfilled','逐产品实际发齐证据','shipping','仓库逐子单履约证据','services/order_line_delivery_service.py','','待接入实发证据；图送达不证明客户收到全部产品'),
    node('after.case','售后记录','after','AfterSales','services/aftersales_auto_service.py'),
    node('after.return','补发与退货单','after','RefillRecord / AfterSales','models/order.py'),
    node('after.payment','退款赔付事实','after','AfterSalesPayment','models/aftersales_payment.py'),
    node('finance.estimate','理论成本估算','finance','Order.theoretical_cost','services/order_cost_service.py','def recompute_and_save'),
    node('finance.actual','实际成本及账单','finance','Order.actual_cost / financial bills','services/order_financials.py','def physical_cost_breakdown'),
    node('finance.profit','利润与期间汇总','finance','net_profit / accounting_summary','services/order_financials.py','def accounting_summary'),
    node('finance.freight','整单运装费用','finance','LogisticsBill / installation bills','models/finance.py'),
    node('settlement.payment','支付流水与月结','settlement','FactorySettlementPayment','services/factory_settlement_service.py','def settle_month'),
    node('settlement.reverse','结算冲销','settlement','reverse_settlement','services/factory_settlement_service.py','def reverse_settlement'),
    node('settlement.period','会计期间与锁定','settlement','AccountingPeriod.status','models/accounting_period.py'),
    node('settlement.expense','工资、押金、期间费用','settlement','staff_salary / shop_deposit','services/staff_salary_service.py'),
    node('marketing.promo','推广、品牌与样品','marketing','Marketing / promotion flows','models/marketing.py'),
    node('marketing.review','评价资产边界','marketing','ReviewAsset','models/review_asset.py','','独立评价程序，不继承ERP生产权限'),
    node('sync.factory','工厂表管理字段','sync','factory_dispatch.build_rows','services/factory_dispatch_feishu_service.py','def build_rows'),
    node('sync.readback','工厂表写后读回','sync','factory_dispatch.sync / preview_diff','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    node('sync.generic','通用表格绑定','sync','FeishuSyncBinding','models/feishu_sync.py','','与专用工厂表单向投影不同'),
    node('sync.manual','工厂手工列','sync','未列入FIELD_SPECS的远程字段','services/factory_dispatch_feishu_service.py','def _business_payload'),
    node('automation.batch','持久批次与文件证据','automation','automation_pipeline_service','services/automation_pipeline_service.py'),
    node('automation.agent','固定Web Agent执行','automation','web_agent_service','services/web_agent_service.py'),
    node('automation.closeout','订单收口与分项结果','automation','complete_recovered_order_delivery','services/order_delivery_completion_service.py','def complete_recovered_order_delivery'),
    node('automation.timer','定时运行记录','automation','ScheduledJobRun','models/scheduled_job.py'),
    node('automation.alert','失败、等待与告警','automation','Alert / DataException','models/alert.py'),
    node('governance.auth','角色与页面权限','governance','User.role / page_perms','dependencies.py','def enforce_page_permission'),
    node('governance.change','字段变更与审计','governance','FieldChange / SystemEvent','models/field_change.py'),
    node('governance.backup','备份与恢复边界','governance','backup_service','services/backup_service.py'),
    node('order.purchase_facts','全部有效购买明细','order','OrderDetail SKU/qty/refund','services/order_purchase_facts.py','def purchase_lines'),
    node('finance.sales_sku','逐SKU销量与未分摊金额','finance','sales product_breakdown','services/sales_analytics.py','def product_breakdown'),
    node('finance.dashboard','月度大盘销售占比','finance','sales_mix','services/dashboard_monthly_service.py','def sales_mix'),
    node('finance.cache','销售缓存与来源指纹','finance','SalesDailyRollup','services/sales_rollup_service.py','def query_summary'),
    node('finance.closeout','限定派生修复与待核实台账','finance','source-bound closeout','services/multi_child_closeout_service.py','def apply'),
    node('stock.demand','逐子SKU需求预测','stock','DemandObservation','services/inventory_demand_service.py','def load_observations'),
]


def edge(a, b, action, condition, check, path, anchor='', kind='data', evidence='code'):
    return {'id': a + '>' + b, 'from': a, 'to': b, 'action': action,
            'condition': condition, 'check': check, 'kind': kind, 'evidence': evidence,
            'sources': [source(path, anchor)]}


EDGES = [
    edge('order.parent','stock.ship_movement','读取母单扣成品现货','有产品/订单ID且原事件尚未记账、有正现货','核对母单qty与全部有效子行；无现货no-op不等于已发齐','services/product_stock_ledger_service.py','def record_shipment'),
    edge('order.child','stock.ship_movement','多子SKU库存覆盖缺口','当前函数读取母单product_code/sku/qty','逐子SKU实际库存扣减未在此入口证明，不能用图或表已同步替代','services/product_stock_ledger_service.py','def record_shipment',kind='gap',evidence='gap'),
    edge('stock.finished','stock.ship_movement','选择可扣现货行','SKU精确匹配优先，否则回退现货最多行','规格回退不等于精确匹配；扣减上限为现存量','services/product_stock_ledger_service.py','def _pick_stock_row',evidence='review'),
    edge('stock.ship_movement','stock.finished','按实际记账take减少现货','唯一reason+entity账本插入成功','take=min(母单qty,现货)；不以本条关系证明客户收到货','services/product_stock_ledger_service.py','def record_shipment'),
    edge('factory.order','stock.restock','区分备货与客户生产单','source_order_id为空且qty为正、原流水不存在','客户MTO到货不自动增加可售现货','services/product_stock_ledger_service.py','def record_restock_receipt'),
    edge('stock.restock','stock.finished','增加成品现货并记入库日期','已插入唯一到货流水','首次备货可能建库存行；不混同物料库存','services/product_stock_ledger_service.py','def record_restock_receipt'),
    edge('stock.ship_movement','stock.reversal','原出库可作为冲正依据','明确调用reverse且能找到原流水','查重、仓库与规格；不能因为图谱提示自动撤销库存','services/product_stock_ledger_service.py','def reverse',kind='protect'),
    edge('stock.reversal','stock.finished','冲正影响现货结余','原库存行存在；现货不低于零','流水冲正量与实际结余变化须对平；不自动复原订单','services/product_stock_ledger_service.py','def reverse',evidence='review'),
    edge('governance.approval','automation.alert','审批待办与状态提醒','create_request建待办；approve/reject处理提示','审批不得自批，非pending不重复批准','services/approval_service.py','def approve'),
    edge('governance.approval','finance.actual','审批状态不是支付凭证','执行器只在action已注册时调用','approved但未注册执行器不证明真实付款；必须核对动作回执','services/approval_service.py','def approve',kind='protect'),
    edge('shipping.confirmed_month','sync.factory','月份说明进入工厂表投影','须另走原同步程序并读回','apply_confirmed_months不发送消息/不同步；月未知日不得造某天','services/factory_shipping_confirmation_service.py','def read_confirmed_months'),
    edge('shipping.confirmed_month','factory.sheet','保留已有生产安排','精确原授权且生命周期无冲突','修改发货月份不取消生产、不重发图、不改其他订单','services/factory_shipping_confirmation_service.py','def apply_confirmed_months',kind='protect'),
    edge('governance.source_index','governance.relationships','扩展变更核查候选范围','反向导入引用有界展开，未识别路径仍输出','代码依赖不是数据传播；缺源码和解析异常不能清零','services/business_relationship_service.py','def review_changes'),
    edge('governance.auth','governance.relationships','复用工具页角色限制','管理员或操作员；仅GET元数据','不读取订单，不调用发送、报名、库存和财务执行器','api/admin.py','def business_relationship_changes',kind='boundary'),
    edge('order.child','order.purchase_facts','读取有效购买行','排除母单汇总/服务/全退，部分退款保留','数量未知不填1；无子行编码不猜','services/order_purchase_facts.py','def _filter_lines'),
    edge('order.purchase_facts','finance.estimate','按全部有效行计算成本','缺价/数量或护栏失败','保留原估值并待核实，不回退首SKU','services/order_cost_service.py','def recompute_and_save'),
    edge('order.purchase_facts','finance.sales_sku','逐子SKU统计购买件数','同一母单现金仅一次','未分摊金额单列；子单待分摊不是零售价','services/order_purchase_facts.py','def sales_projections'),
    edge('finance.sales_sku','finance.dashboard','保持金额守恒与子单数量','月度实时数据','入户玄关柜不是服务；真实账单不改','services/dashboard_monthly_service.py','def sales_mix'),
    edge('order.purchase_facts','finance.cache','刷新可再生销售缓存','订单/子单来源指纹一致','过期返回实时查询；毛估利润不是会计净利','services/sales_rollup_service.py','def _source_fingerprints'),
    edge('order.purchase_facts','stock.demand','逐子SKU进入预测与未发需求','保留已有预测清洗政策','不复制母单金额到每个子SKU；未知状态不判已发','services/inventory_demand_service.py','def current_unshipped_standard_qty'),
    edge('order.child','sync.readback','检查全量实体覆盖','旧汇总只做历史保留；旧记录唯一绑定','未匹配子单不能宣称同步成功','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    edge('finance.estimate','finance.closeout','源文件与完整SKU核对后修派生值','只处理可证明分项；关账期间不改','实际付款/账单保护；未决写异常台账','services/order_completeness_incident.py','def all_product_financial_plan'),
    edge('finance.closeout','finance.cache','一次重建当前年派生缓存','精确计划hash、事务锁及防重复回执','不重新导单/发图/修改真实账单','services/multi_child_closeout_service.py','def apply'),
    edge('npd.project','npd.gate','阶段门检查','切换阶段时','未完成必做任务/检验不得混同已通过','services/npd_service.py','def move_project'),
    edge('npd.gate','npd.materialize','核对建档资格','操作员请求建档；具体门分支须复核','阶段切换不等于自动正式化','services/npd_service.py','def materialize_project',evidence='review'),
    edge('npd.materialize','product.identity','生成正式商品','有BOM且未曾建档','重复建档拒绝','services/npd_service.py','def materialize_project'),
    edge('npd.materialize','bom.lines','生成正式BOM','明确建档动作','物料编码、数量、单价逐项核对','services/npd_service.py','def materialize_project'),
    edge('npd.materialize','price.current','生成草稿定价','建档成功','草稿不是已批准渠道售价','services/npd_service.py','def materialize_project'),
    edge('product.identity','product.sku','产品-规格关联','精确product_code','多规格不得合并','models/pricing.py'),
    edge('product.sku','product.dimensions','选择精确尺寸','同SKU及验证hash','不得使用其他变体图','services/factory_production_evidence.py','def verified_dimensions'),
    edge('product.custom','factory.sheet','定制尺寸优先','精确变体存在','缺尺寸保留待核实','services/factory_sheet.py','def build_from_fields'),
    edge('bom.material','bom.drift','触发成本核对','物料变更且SKU使用此物料','只核相关SKU，不改售价','services/pricing_bom_sync_service.py','def check_for_material'),
    edge('bom.lines','bom.drift','计算BOM成本差异','有可计算的物料价格','空价格不当零','services/pricing_bom_sync_service.py','def check_sku'),
    edge('bom.drift','price.current','禁止自动改售价','成本漂移只产生提示','售价仍由原定价流程决定','services/pricing_bom_sync_service.py',kind='protect'),
    edge('price.formula','price.current','派生价格字段','显式重算入口','日常/中促/大促口径不能互换','services/pricing_calc_service.py'),
    edge('price.current','price.version','保存价格版本','版本服务入口','历史版本边界需核对','services/pricing_version_service.py',evidence='review'),
    edge('price.version','finance.estimate','按订单日期取价','历史快照存在','不得用现价覆盖历史依据','services/order_cost_service.py','def _asof_pricing'),
    edge('product.sku','campaign.mapping','规格身份映射','ERP编码与平台SKU唯一','缺失不猜映射','models/sku_identity.py'),
    edge('campaign.mapping','campaign.files','选择报名范围','ERP可售∩淘宝上架','排除无对应仅限本场文件','services/campaign_workflow_service.py',evidence='review'),
    edge('price.current','campaign.files','填价格与优惠','同价版本/精确窗口','普通报名价=日常价；容差不逐轮累计','services/campaign_workflow_service.py',evidence='review'),
    edge('campaign.window','campaign.files','绑定模板与窗口','当次官方身份','不复用旧已填数据','services/campaign_workflow_service.py',evidence='review'),
    edge('campaign.files','campaign.receipt','固定程序提交并取终态','一次claim且非成功/未知','上传成功不是报名成功','services/campaign_workflow_service.py',evidence='review'),
    edge('order.file','order.parent','导入母单字段','原始导入档案','缺列不清空现有事实','services/taobao_order_import.py'),
    edge('order.parent','order.child','关联全部购买行','存在source=import','不得只取第一件；全过滤后不退回母单','services/order_line_delivery_service.py'),
    edge('order.child','order.qty','保留逐子单购买数','原始购买明细','缺失/0不是1','models/order.py','class OrderDetail'),
    edge('order.qty','quantity.card','需要时询问成品数','未知购买数或定制多计价单位','普通有效数量不强制询问','services/factory_quantity_request_service.py','def request_quantity'),
    edge('quantity.card','quantity.reply','等待真人回复','回复对应卡且来自正确群','群里孤立数字不能确认','services/factory_quantity_request_service.py','def handle_reply'),
    edge('quantity.reply','quantity.physical','记录确认依据','真实消息读回且身份未变化','确认人/回复/精确子单齐全，冲突不覆盖','services/factory_production_evidence.py','def confirm_quantity'),
    edge('order.notes','quantity.physical','使旧确认失效','备注/购买数/SKU身份发生变化','不能沿用旧卡默认为已确认','services/factory_production_evidence.py','def _identity'),
    edge('quantity.physical','factory.sheet','取成品量制单','确认记录与当前身份相符','购买量仍原值；材料按成品量','services/factory_sheet.py','def build_for_order_line'),
    edge('order.qty','factory.sheet','普通购买数作为成品数','有效数量且无定制计价歧义','0/空/负数必须待确认','services/factory_sheet.py','def build_for_order_line'),
    edge('product.dimensions','factory.sheet','读取精确尺寸','SKU/产品/hash一致','错变体和过期hash不通过','services/factory_sheet.py','def build_from_fields'),
    edge('bom.lines','factory.sheet','生成物料需求','BOM×确认成品数','未知数不能作为正式生产单','services/factory_sheet.py','def build_from_fields'),
    edge('order.customer','factory.sheet','收货信息和备注','地址未脱敏或明确待补分支','信息待补不捏造地址','services/factory_sheet.py','def build_for_order_line'),
    edge('factory.sheet','factory.receipt','固定逐子单发送','生产事实合格且未送达/未占用','未知发送不盲重试','services/order_sheet_archive_service.py'),
    edge('factory.receipt','factory.archive','存已发内容快照','真实图片message_id','按SKU/数量/hash审计，不用母单sent替代','services/order_sheet_archive_service.py','def archive_sent_line_snapshot'),
    edge('order.refund','factory.void','确定作废或停用范围','精确子单关闭/退款','不得作废有效兄弟单','services/order_line_delivery_service.py'),
    edge('quantity.physical','order.qty','禁止覆盖原购买量','数量确认仅供生产','交易数量保持不变','services/factory_production_evidence.py','def confirm_quantity',kind='protect'),
    edge('quantity.physical','finance.actual','禁止修改实际账单','成品数确认','不得自动改实付/已结账金额','services/factory_production_evidence.py','def confirm_quantity',kind='protect'),
    edge('order.child','finance.estimate','汇总全部有效产品成本','排除退款/非实体行','同SKU多件也要累计','services/order_cost_service.py','def _multi_product_cost'),
    edge('finance.estimate','finance.actual','禁止估算覆盖实账','recompute_and_save','actual_cost不清空或重写','services/order_cost_service.py','def recompute_and_save',kind='protect'),
    edge('finance.estimate','finance.profit','缺实际时的估算口径','遵守成本优先级','展示估算/实账差异','services/order_financials.py','def cost_breakdown'),
    edge('finance.actual','finance.profit','汇总真实分项成本','账单匹配及口径正确','木作不等于全部成本','services/order_financials.py','def physical_cost_breakdown'),
    edge('finance.freight','finance.profit','计入整单费用','费用已匹配','不擅自均摊到每个子SKU','services/order_financials.py','def cost_breakdown'),
    edge('factory.order','stock.lock','生成物料占用','工厂单发起锁库','锁库不代表消耗','services/inventory_lock_service.py','def lock_for_factory_order'),
    edge('bom.lines','stock.lock','BOM决定占用量','精确SKU/工厂单','单位、数量、锁库身份一致','services/inventory_lock_service.py','def lock_for_factory_order'),
    edge('stock.lock','stock.consume','发货消耗/取消释放','不同明确动作','释放和消耗不得重复执行','services/inventory_lock_service.py','def consume_for_shipment'),
    edge('stock.consume','stock.balance','更新库存台账','合法流水','结余与流水一致','services/inventory_lock_service.py','def consume_for_shipment'),
    edge('purchase.quote','purchase.parts','采购决策后建单','原采购流程','询价不等于授权下单','services/procurement_service.py',evidence='review'),
    edge('purchase.supplier','purchase.quote','供应商关联','候选与选定区分','不自动付款','services/procurement_service.py',evidence='review'),
    edge('purchase.parts','stock.inbound','采购到货入库','入库动作','到货不能重复增加库存','services/inventory_lock_service.py','def inbound_part'),
    edge('stock.inbound','stock.balance','写入库存流水','入库/退回/拆解各自身份','撤销必须关联原流水','services/inventory_lock_service.py','def return_in_product'),
    edge('shipping.tracking','shipping.status','同步轨迹派生状态','entity_type限定','同运单不同实体不得错绑','services/shipment_service.py','def _apply_derivation'),
    edge('shipping.status','shipping.fulfilled','需要逐项实发核验','仅包裹签收不能证明全商品发齐','核对每个子单实发数量/包裹内容','services/shipment_service.py',kind='gap',evidence='gap'),
    edge('factory.receipt','shipping.fulfilled','禁止把发图当发货','两种外部事实不同','仓库和客户履约回执独立','services/order_line_delivery_service.py',kind='protect'),
    edge('order.refund','after.case','创建售后记录','退款同步条件满足','生成记录不等于退款或补发完成','services/aftersales_auto_service.py'),
    edge('after.case','after.return','售后处理与补件','人工确认补发/退货','不得变成重复原单生产','models/order.py',evidence='review'),
    edge('after.return','stock.inbound','退回二次入库','签收且入库确认','物流签收和库存记账分开','services/inventory_lock_service.py','def return_in_product'),
    edge('after.payment','finance.profit','售后费用归集','真实赔付记录','不由图触发支付','services/order_financials.py','def extra_aftersales'),
    edge('settlement.payment','settlement.reverse','按原支付记录冲销','明确反结算动作','不删除真实交易事实','services/factory_settlement_service.py','def reverse_settlement'),
    edge('settlement.period','finance.profit','期间口径','月/期间边界','锁定期间不能因结构分析重算','services/accounting_period_service.py',evidence='review'),
    edge('settlement.expense','finance.profit','期间费用归集','费用类型和日期','未分配费用不编造单件成本','services/order_financials.py','def accounting_summary',evidence='review'),
    edge('marketing.promo','finance.profit','推广期间费用','费用确认和日期范围','推广充值与实际消耗不同','services/order_financials.py','def accounting_summary',evidence='review'),
    edge('marketing.review','order.child','外部评价边界','只在批准数据合同内关联','不自动抓取客户/执行评价','models/review_asset.py',kind='boundary',evidence='review'),
    edge('factory.sheet','sync.factory','复用生产事实投影','每个有效子单','成品数、购买数、尺寸和确认状态一致','services/factory_dispatch_feishu_service.py','def build_rows'),
    edge('order.refund','sync.factory','有效生产范围核对','精确子单关闭/退款','不连带删除兄弟单','services/factory_dispatch_feishu_service.py','def _line_void'),
    edge('factory.receipt','sync.factory','已发图附件绑定','编号/图片签名相符','不以任意最新图冒充正式已发图','services/factory_dispatch_feishu_service.py','def build_rows'),
    edge('sync.factory','sync.readback','增量投影并读回','单写锁且原自动同步启用','写入回执与字段一致各自检查','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    edge('sync.factory','sync.manual','禁止覆盖工厂手工列','只允许FIELD_SPECS字段','未管理列保持原样','services/factory_dispatch_feishu_service.py','def _business_payload',kind='protect'),
    edge('sync.generic','sync.factory','两类表同步不等价','专用表单向/通用表按绑定','不得继承通用双向写回规则','models/feishu_sync.py',kind='boundary'),
    edge('quantity.reply','sync.readback','更新确认后的工厂投影','图回执独立；表失败保留','不能因表失败重发正式图','services/factory_quantity_request_service.py','def handle_reply'),
    edge('automation.batch','automation.agent','交给固定程序执行','一次持久批次','AI不逐步操控浏览器','services/web_agent_service.py',evidence='review'),
    edge('automation.agent','automation.order_owner','读取原订单运行者状态','原batch/attempt/date严格一致','网络失败不是空闲；Web Agent跨程序实际加载需另验','services/web_agent_service.py','def order_receipt_status',evidence='review'),
    edge('automation.order_owner','sync.freshness','完整终态才恢复原批报表','三报表角色/路径/hash匹配','中断或未知进入维护；不重复导入已绑定文件','services/agent_ingest_service.py','def recover_order_receipt'),
    edge('automation.agent','order.file','取回报表证据','batch/attempt/hash匹配','超时结果未知不重复拉取','services/web_agent_service.py',evidence='review'),
    edge('automation.batch','automation.closeout','恢复已导入批次','身份与日期一致','历史批次不改当天状态','services/order_delivery_completion_service.py'),
    edge('automation.closeout','factory.receipt','完成待发图片','精确发送账本保护','已送达/未知不重放','services/order_delivery_completion_service.py'),
    edge('automation.closeout','sync.readback','独立工厂投影收口','图失败不吞掉表结果','表关闭不称已同步；整体错误保留','services/order_delivery_completion_service.py'),
    edge('automation.timer','automation.batch','定时调度批次','原调度设置启用','不增加AI监工定时','services/scheduler.py',evidence='review'),
    edge('automation.closeout','automation.alert','记录失败及等待','分项结果明确','未知/待人工不能涂绿','services/order_delivery_completion_service.py'),
    edge('governance.auth','automation.batch','访问与动作边界','既有角色/页面权限','图不扩张业务权限','dependencies.py','def require_role',kind='boundary'),
    edge('governance.change','sync.generic','保留字段来源和变更','原同步入口','变更记录不等于外部已更新','services/feishu_sync_service.py',evidence='review'),
    edge('governance.backup','factory.receipt','恢复不授权重放发送','恢复数据库后','必须重新对账消息/发送账本','services/backup_service.py',kind='protect'),
    edge('quantity.physical','stock.lock','成品数量变化需核对用料','物料占用是否已按新成品数更新待验证','只提醒核对，不自动改库存台账','services/inventory_lock_service.py',kind='gap',evidence='gap'),
]

# Execution remains in the existing programs. These are review relationships,
# not new workflow steps and not an assertion that a deployment has run them.
NODES += [
    node('campaign.entry','活动报名入口与官方发现','campaign','03｜畔色活动报名 / checked_snapshot','services/campaign_official_discovery.py','def checked_snapshot','日常入口为03；官方入口识别店铺、活动ID及时间。日历日期不等于精确价格窗口，不猜网址。'),
    node('campaign.schedule','活动定时与连续执行接入','campaign','run_auto_execute / continuous runtime','services/campaign_automation_service.py','def run_auto_execute','ERP调度交给本机Web Agent持久执行；不会回退旧预检链。登记程序不表示定时现已开启或验收通过。'),
    node('campaign.controller','Web Agent固定程序边界','campaign','continuous capabilities / dispatch','services/campaign_continuous_runtime.py','def dispatch','ERP通过接口交接；本机Web-Agent的campaign_continuous_worker与ERP scripts/campaign_continuous_execute.py执行。先单品立减、再超级立减、再同窗口主题活动是已约定业务顺序，不代表本场已执行。这里核对的是ERP接口，不冒充外部程序实时指纹。AI只看开头和终态，不分步接管浏览器。'),
    node('campaign.product_export','活动商品全量导出与SKU核对','campaign','parse_product_batch_export / 商品ID+SKU ID','services/campaign_recon_service.py','def parse_product_batch_export','商品文件核对出售中商品与ERP映射；实际导出由固定Web Agent执行。页面总数、总页数、文件范围仍需独立核验。'),
    node('campaign.failure','活动失败报告与隔离修正','campaign','scripts/campaign_failure_remediation.py / report_from_download','services/campaign_continuous_runtime.py','def dispatch','跨程序职责：固定程序下载失败报告、核对无对应SKU并只重报变化后的失败范围。官方本场无动销本场跳过，下场重试；成功/未知不重传。ERP接口源码不能单独证明这些外部分支已验收。'),
    node('campaign.attempt','报名批次与防重放账本','campaign','CampaignExecutionAttempt.scope_sha256 / write_claimed','services/campaign_execution_service.py','def claim_platform_write','活动、窗口、商品SKU、价格和政策绑定同一范围；成功及未知写入不重放。'),
    node('campaign.policy','普通价差与定制底线','campaign','frozen campaign policy / resolve','services/campaign_policy_service.py','def require_policy','普通报名价保持ERP日常价，同一目标累计±2元；定制按首次固定基线20%。这是原规则，不新增价格授权。'),
    node('campaign.baseline','首次定制原价与轮换槽位','campaign','CampaignSkuSlot / immutable_baseline','services/campaign_sku_slot_service.py','def immutable_baseline','定制基线不随降价或轮换重设；缺基线不能编造。槽位存在不表示已获本次轮换授权。'),
    node('campaign.rotation','SKU轮换人工确认边界','campaign','rotation_enabled / rotation_block_result','services/campaign_price_protection_service.py','def rotation_enabled','超过允许价差或触及底线时进入待确认；图中箭头不授权自动轮换，不改变库存或上架状态。'),
    node('campaign.reconcile','活动报名覆盖与价格核对','campaign','reconcile / resolve_current_activity_records','services/campaign_recon_service.py','def reconcile','按本场官方商品/SKU记录核对窗口、覆盖和最终价；上传完成不等于全量成功。超级立减因大促暂停须结合活动身份核对。'),
    node('campaign.notice','活动通知开关','campaign','campaign_notifications_enabled','services/campaign_notification_service.py','def enabled','ERP活动通用通知受独立开关控制；不代表Web Agent终态通知同走这一开关，不影响其他ERP告警。'),
    node('sync.campaign_terminal','飞书活动终态通知','sync','campaign_terminal / delivered / channel','api/web_agent.py',"if payload.kind == 'campaign_terminal':",'本机Web Agent终态发件箱去重；ERP仅交付飞书提醒路由，不回退微信或订单群。通知失败不等于报名失败；此处不能据群消息判断全部SKU成功。'),
    node('sync.route','飞书订单群与提醒群分流','sync','notify_route_mode / feishu_push_chat_id / feishu_alert_chat_id','services/notify_service.py','def get_alert_chat_id','只展示配置字段名，不读取真实群ID、webhook、密钥或客户消息。通用兼容路由与活动专用终态路由分开。'),
    node('sync.inbound','飞书消息与卡片回调','sync','message_id / event_id / card action','services/feishu_ws_service.py','def _on_message','消息入队、旧事件过滤与去重；收到回调不表示业务处理完成。'),
    node('sync.password','飞书报表口令与解密结果','sync','apply_shipping_password / pending files','services/feishu_bot_service.py','def apply_shipping_password','只展示流程，不展示或保存口令到关系目录。收到口令、成功解密、完成导入是不同状态。'),
    node('sync.freshness','报表批次完整性与续跑','sync','finalize_order_pull_after_shipping_password','services/agent_ingest_service.py','def finalize_order_pull_after_shipping_password','绑定本批报表、待解密文件及新鲜度；不能拿旧报表或收到密码消息冒充本批完成。'),
    node('sync.file_card','飞书文件识别与确认入库卡','sync','_file_confirm_card / process_pick','services/feishu_bot_service.py','def _file_confirm_card','订单表、采购单、供应商送货单、工厂对账单等先区分类型；确认卡响应不等于入库完成。'),
    node('sync.import','飞书文件与图片分类导入','sync','_dispatch_file / _dispatch_import','services/feishu_bot_service.py','def _dispatch_import','按文件/图片类型进入各自既有导入器；供应商归属、待确认和导入结果不可混为一谈。'),
    node('sync.conflict','飞书通用表字段冲突','sync','system_hash / feishu_hash / resolve_conflict','services/feishu_sync_service.py','def _sync_one','双向绑定双方改动进入冲突；单向out按系统值维护管理字段。专用工厂表不套用通用表规则。'),
    node('sync.mapping','飞书表行身份与同步回执','sync','FeishuRecordMap / record_id / hashes','services/feishu_sync_service.py','def _flush_push_batch','绑定、系统主键、飞书record_id与字段映射对应；批量发送成功后更新映射，不以任务已启动代表同步完成。'),
    node('sync.remote','飞书远期单报备提醒','sync','reminder_card / confirm','services/remote_report_service.py','def confirm','人工在淘宝处理后点击确认。飞书确认记录是人工声明，不是程序已在淘宝延期的官方回执。'),
    node('sync.inspection','飞书工厂验货图归档','sync','_process_inspection_post','services/feishu_bot_service.py','def _process_inspection_post','按订单引用归档验货图；归档不等于逐子单发齐或物流签收。'),
]

# Replace the old prepare-only -> official-success shortcut with the real
# preparation / execution / readback boundary. Do not retain a misleading edge.
EDGES = [e for e in EDGES if e['id'] != 'campaign.files>campaign.receipt']
EDGES += [
    edge('campaign.entry','campaign.window','官方身份与精确窗口','官方页面完整且店铺匹配','日历仅到天时不能补造秒级窗口','services/campaign_official_discovery.py','def checked_snapshot'),
    edge('campaign.schedule','campaign.controller','接入固定连续执行器','原调度启用且接入就绪','不回退旧链；dispatch结果不代表业务完成','services/campaign_automation_service.py','def run_auto_execute'),
    edge('campaign.files','campaign.controller','准备与执行分离','ERP准备完成后由已有执行程序接手','workflow_service仅准备，不操控网页；具体外部版本另核','services/campaign_continuous_runtime.py','def dispatch',kind='boundary'),
    edge('campaign.controller','campaign.attempt','程序写入范围核对','同一精确范围和持久请求','连续程序与ERP账本的跨程序一致性需核对，不能仅凭一个prepared状态提交','services/campaign_execution_service.py','def ensure_attempt',evidence='review'),
    edge('campaign.attempt','campaign.receipt','持久记录官方结果','已经声明写入的范围','成功/失败/未知分开；未知不自动重传','services/campaign_execution_service.py','TERMINAL_NO_RETRY_STATES'),
    edge('campaign.policy','campaign.files','沿用冻结价格规则','同一价格版本和精确窗口','不把普通价差让步变成改ERP日常价；连续脚本与ERP规则入口需交叉核对','services/campaign_policy_service.py','def require_policy',evidence='review'),
    edge('campaign.product_export','campaign.mapping','解析官方商品事实','完整导出且商品ID+SKU ID唯一匹配','无对应仅从本场失败报名范围移除；不删除商品或改库存','services/campaign_recon_service.py','def parse_product_batch_export',evidence='review'),
    edge('campaign.controller','campaign.failure','固定程序收集本场失败报告','本场真实失败且下载结果可验证','入口不可用或登录交互需说明最小人工操作，不自由操控重试','services/campaign_continuous_runtime.py','def dispatch',kind='boundary',evidence='review'),
    edge('campaign.failure','campaign.product_export','不存在SKU的事实核对','仅受影响范围需要补足商品证据','已有同范围新鲜文件可复用；不是每步重新导出','services/campaign_recon_service.py','def parse_product_batch_export',evidence='review'),
    edge('campaign.failure','campaign.policy','按原规则分类失败','本场官方失败商品和SKU','小额差按同一基准累计，不逐轮放宽；缺数据不猜','services/campaign_policy_service.py','def require_policy',evidence='review'),
    edge('campaign.baseline','campaign.policy','定制底线计算依据','首次原价已固定','不低于原基线20%；缺失保留待确认','services/campaign_price_resolution_service.py','def resolve'),
    edge('campaign.policy','campaign.rotation','超界后的人工分支','原规则不允许直接修正','不因程序失败自动更换SKU','services/campaign_price_protection_service.py','def rotation_block_result',kind='protect'),
    edge('campaign.rotation','campaign.mapping','轮换后的身份影响','仅本次明确授权且平台保存读回','新旧SKU映射/属性/报名范围需核对；不扩大其他商品','services/campaign_sku_slot_service.py','def finalize_switch',evidence='review'),
    edge('campaign.receipt','campaign.reconcile','官方结果覆盖核对','当场活动导出与精确商品SKU','不能把部分结果当全量通过','services/campaign_recon_service.py','def resolve_current_activity_records'),
    edge('price.current','campaign.reconcile','价格目标核对','同一价格口径','日常价/活动价/券后价不可混用','services/campaign_recon_service.py','def reconcile'),
    edge('campaign.reconcile','campaign.notice','价格及覆盖异常通知','现有对账告警条件','通知开关关闭不等于异常已处理','services/campaign_recon_service.py','def reconcile'),
    edge('campaign.notice','sync.route','ERP活动通用通知分流','campaign_notifications_enabled启用','不要据此推断专用终态通知也受该开关控制','services/campaign_notification_service.py','def broadcast_text'),
    edge('campaign.controller','sync.campaign_terminal','本机终态发件箱交付ERP','已有专用终态协议','外部发件箱状态须独立核对，不能从ERP接口源码推断已送达','api/web_agent.py',"if payload.kind == 'campaign_terminal':",kind='boundary'),
    edge('sync.campaign_terminal','sync.route','仅飞书提醒群','专用路由就绪','不回退微信/订单群；发送不成功不能重跑报名','api/web_agent.py',"if payload.kind == 'campaign_terminal':",kind='protect'),
    edge('sync.campaign_terminal','campaign.receipt','消息与报名回执独立','通知已发或失败均如此','飞书已送达不是全量报名证明，不能覆盖官方结果','api/web_agent.py',"if payload.kind == 'campaign_terminal':",kind='protect'),
    edge('sync.inbound','quantity.reply','分流真实数量回复','先识别原卡片/子单和真实发言人','不把任意数字消息作为数量确认','services/feishu_bot_service.py','def on_message_event'),
    edge('sync.inbound','sync.password','分流发货报表口令','文本命中口令入口','只处理对应待解密文件，不把口令写入关系日志','services/feishu_bot_service.py','def on_message_event'),
    edge('sync.password','sync.freshness','解密后核验本批完整性','已导入与待解密状态重新核对','收到口令不直接放行制单','services/feishu_bot_service.py','def apply_shipping_password'),
    edge('sync.freshness','automation.closeout','续跑订单交付','本批报表完成且业务条件满足','已发/未知不重放；图、表分别记结果','services/agent_ingest_service.py','def finalize_order_pull_after_shipping_password'),
    edge('sync.inbound','sync.file_card','文件/图片分类确认','真实消息和资源已接收','不把识别置信度当人工确认','services/feishu_bot_service.py','def _on_file_message'),
    edge('sync.file_card','sync.import','确认后进入分类导入','有效原消息及选择类型','送货单先核供应商；回调toast不是入库结果','services/feishu_ws_service.py','def _on_card'),
    edge('sync.import','order.child','订单导入影响逐子单','文件类型确为订单且解析成功','核验全部子单/购买数量，不能只看母单总数','services/feishu_bot_service.py','def _import_orders',evidence='review'),
    edge('sync.import','finance.actual','账单导入影响实际成本','真实类型和供应商/工厂归属','OCR结果仍需核对，不把制单估价替代账单','services/feishu_bot_service.py','def _dispatch_import',evidence='review'),
    edge('sync.generic','sync.conflict','按绑定方向比较两侧变化','字段映射和主键明确','双向两侧改动不得静默覆盖；out方向按既有规则','services/feishu_sync_service.py','def _sync_one'),
    edge('sync.conflict','sync.mapping','人工解决冲突后记录映射','明确保留侧或字段选择','未知字段/类型冲突不能强行覆盖','services/feishu_sync_service.py','def resolve_conflict'),
    edge('sync.generic','sync.mapping','批量同步记录身份','实际外部记录返回成功','请求启动不能当写入完成','services/feishu_sync_service.py','def _flush_push_batch'),
    edge('sync.mapping','governance.change','飞书修改保留字段历史','允许pull且飞书侧发生变更','回写权限受绑定限制，不影响未绑定字段','services/feishu_sync_service.py','def _sync_one'),
    edge('sync.inbound','sync.remote','报备确认卡分支','有效confirm_remote_report操作','人工确认记录不代替淘宝真实处理','services/feishu_ws_service.py','def _on_card'),
    edge('order.notes','sync.remote','备注识别远期订单','命中既有远期关键词','未确认后续继续提醒，非自动延期','services/remote_report_service.py','def matched_keyword'),
    edge('sync.inbound','sync.inspection','工厂验货图分流','有效订单引用和图片','未找到订单不挂错单','services/feishu_bot_service.py','def _process_inspection_post'),
    edge('sync.inspection','shipping.fulfilled','验货与实发分开','有验货归档仍需逐子单实发证据','不能把图片归档当所有商品已发齐','services/feishu_bot_service.py','def _process_inspection_post',kind='protect'),
]

FLOWS = [
    {'id':'campaign-execution','name':'活动报名程序：官方发现 → ERP准备 → Web Agent → 官方对账 → 飞书',
     'steps':['campaign.entry','campaign.window','campaign.files','campaign.controller','campaign.attempt','campaign.receipt','campaign.reconcile','sync.campaign_terminal']},
    {'id':'campaign-exceptions','name':'活动失败处理：价格规则 → 基线 → 人工轮换 → 映射与重新核对',
     'steps':['campaign.failure','campaign.product_export','campaign.policy','campaign.baseline','campaign.rotation','campaign.mapping','campaign.files','campaign.receipt']},
    {'id':'feishu-password','name':'飞书口令：消息 → 解密 → 本批完整性 → 制单与工厂表',
     'steps':['sync.inbound','sync.password','sync.freshness','automation.closeout','factory.receipt','sync.factory','sync.readback']},
    {'id':'feishu-import','name':'飞书文件/图片：确认卡 → 分类导入 → 子单、财务与追溯',
     'steps':['sync.inbound','sync.file_card','sync.import','order.child','finance.actual','governance.change']},
    {'id':'feishu-binding','name':'飞书通用表：绑定方向 → 字段冲突 → 行回执与修改历史',
     'steps':['sync.generic','sync.conflict','sync.mapping','governance.change','sync.manual']},
    {'id':'feishu-cards','name':'飞书业务分支：数量回复、远期报备、验货图（非串行）',
     'steps':['sync.inbound','quantity.reply','quantity.physical','sync.remote','sync.inspection','sync.readback']},
    {'id':'finished-stock','name':'成品现货 → 母单扣库/备货入库 → 冲正与子SKU覆盖核查',
     'steps':['order.parent','order.child','stock.finished','stock.ship_movement','factory.order','stock.restock','stock.reversal','shipping.fulfilled']},
    {'id':'approval','name':'人工审批 → 注册执行器 → 独立结果与告警核对',
     'steps':['governance.auth','governance.approval','automation.alert','finance.actual','governance.change']},
    {'id':'maintenance','name':'程序变更 → 依赖候选 → 业务影响与保护检查',
     'steps':['governance.auth','governance.source_index','governance.relationships','governance.change','governance.backup']},
    {'id':'automation','name':'定时与文件 → 固定程序 → 分项收口与告警',
     'steps':['automation.timer','automation.batch','automation.agent','order.file','automation.closeout','factory.receipt','sync.readback','automation.alert']},
    {'id':'sync','name':'数量/制单事实 → 工厂表 → 独立读回与手工字段保护',
     'steps':['quantity.reply','factory.sheet','factory.receipt','sync.factory','sync.readback','sync.manual','sync.generic']},
    {'id':'after','name':'子单退款 → 售后 → 退回入库与费用核对',
     'steps':['order.refund','after.case','after.return','stock.inbound','after.payment','finance.profit']},
    {'id':'settlement','name':'实际账单 → 月结支付 → 冲销与会计期间',
     'steps':['finance.actual','finance.freight','finance.profit','settlement.payment','settlement.reverse','settlement.period','settlement.expense']},
    {'id':'marketing','name':'推广样品与评价 → 费用/订单及系统权限边界',
     'steps':['marketing.promo','marketing.review','order.child','finance.profit','governance.auth']},
    {'id':'reporting','name':'全部子单 → 销量 → 财务及大盘 → 缓存核验',
     'steps':['order.child','order.purchase_facts','finance.estimate','finance.sales_sku','finance.dashboard','finance.cache','stock.demand']},
    {'id':'order','name':'订单 → 数量确认 → 制单 → 工厂表',
     'steps':['order.file','order.child','order.qty','quantity.card','quantity.reply','quantity.physical','factory.sheet','factory.receipt','sync.factory','sync.readback']},
    {'id':'product','name':'研发 → 商品 → BOM → 定价',
     'steps':['npd.project','npd.gate','npd.materialize','product.identity','product.sku','bom.lines','bom.drift','price.current']},
    {'id':'campaign','name':'价格与映射 → 活动 → 官方结果',
     'steps':['price.current','campaign.mapping','campaign.window','campaign.files','campaign.receipt']},
    {'id':'fulfillment','name':'采购生产 → 库存 → 物流 → 售后',
     'steps':['purchase.quote','purchase.parts','factory.order','stock.lock','stock.consume','stock.balance','shipping.tracking','shipping.status','shipping.fulfilled','after.case','after.return']},
    {'id':'finance','name':'购买行与历史价 → 成本 → 财务结算',
     'steps':['order.child','price.version','finance.estimate','finance.actual','finance.freight','after.payment','finance.profit','settlement.payment','settlement.period']},
]
