"""Reviewed business semantics, NOT executable workflow or runtime receipts.

Keep stable IDs. Sources are repository-relative metadata, never customer data.
Every edge describes a checkable contract rather than inferred import lineage.
"""
VERSION = '2026-09-21.2'
DOMAINS = [
    ('npd', '新品研发', '产品'), ('product', '商品与规格', '产品'),
    ('bom', '物料与BOM', '产品'), ('price', '定价与版本', '价格'),
    ('campaign', '渠道与活动', '运营'), ('order', '客户与订单导入', '订单'),
    ('quantity', '定制数量确认', '人工确认'), ('factory', '工厂与制单', '工厂'),
    ('purchase', '采购与配件', '采购'), ('stock', '库存与齐套', '仓库'),
    ('shipping', '物流与安装', '物流'), ('after', '售后与补发', '售后'),
    ('finance', '财务与对账', '财务'), ('settlement', '付款与经营', '财务'),
    ('marketing', '营销与反馈', '运营'), ('sync', '飞书与外部投影', '飞书'),
    ('automation', '自动化与异常', '程序'), ('governance', '权限与追溯', '维护'),
]


def source(path, anchor=''):
    return {'path': 'backend/app/' + path, 'anchor': anchor}


def node(id, label, domain, field, path, anchor='', note=''):
    return {'id': id, 'label': label, 'domain': domain, 'field': field,
            'sources': [source(path, anchor)], 'note': note}


NODES = [
    node('stock.finished','成品现货与规格选择','stock','ProductInventory.physical_qty / sku','services/product_stock_ledger_service.py','def _pick_stock_row','现存规格回退分支需核实；不能视为精确子SKU库存证明'),
    node('stock.ship_movement','母单发货扣成品现货','stock','ProductStockMovement reason=ship entity=order','services/product_stock_ledger_service.py','def record_shipment','当前入口读取母单product_code/sku/qty，不证明多子SKU均已扣库'),
    node('stock.restock','备货单到货入成品库','stock','FactoryOrder.source_order_id / qty','services/product_stock_ledger_service.py','def record_restock_receipt','客户单MTO不计入可售现货'),
    node('stock.reversal','成品库存冲正流水','stock','ProductStockMovement reason=reversal','services/product_stock_ledger_service.py','def reverse','冲正现存流水，不据关系图执行库存调整'),
    node('governance.approval','审批状态与执行器','governance','ApprovalRequest / _EXECUTORS','services/approval_service.py','def approve','approved状态不单独证明执行器存在及动作实际完成'),
    node('shipping.confirmed_month','人工确认发货月份','shipping','Order.customer_shipping_month','services/factory_shipping_confirmation_service.py','def apply_confirmed_months','仅既有两笔精确授权；月份不补造日期，不改变生产权限'),
    node('governance.relationships','业务影响检查清单','governance','review_changes / flow_review','services/business_relationship_service.py','def review_changes','只读维护工具，不增加报名和订单执行前置门'),
    node('governance.source_index','全程序静态引用索引','governance','source_index / dependency_review','services/business_relationship_index.py','def source_index','索引候选不等于业务语义已审查；发布快照与运行源码区分'),
    node('npd.project','研发项目与阶段','npd','NpdProject / NpdStageInstance','models/npd.py'),
    node('npd.gate','任务、检验及成本关口','npd','NpdTask / NpdInspectionItem / NpdCostGate','services/npd_service.py','def move_project'),
    node('npd.materialize','设计正式建档','npd','materialize_project','services/npd_service.py','def materialize_project'),
    node('product.identity','产品身份','product','Product.code','models/product.py','class Product'),
    node('product.sku','规格身份','product','PricingSku.sku_code / product_code','models/pricing.py','class PricingSku'),
    node('product.dimensions','精确规格尺寸','product','PricingSku.size_info / verified_dimensions','services/factory_production_evidence.py','def verified_dimensions','不以其他变体或产品默认图替代'),
    node('product.custom','定制变体','product','CustomVariant.dimension_overrides','models/custom_variant.py'),
    node('bom.material','物料单价','bom','Material.price','models/material.py'),
    node('bom.lines','BOM单位用量','bom','BomLine.qty_per_product','models/bom.py'),
    node('bom.drift','成本差异提醒','bom','check_sku / check_for_material','services/pricing_bom_sync_service.py','def check_sku','只核查和提示，不自动调售价'),
    node('price.current','日常/中促/大促价格','price','PricingSku.daily_price / mid_promo / big_promo','models/pricing.py'),
    node('price.version','历史价格版本','price','PricingVersion','services/pricing_version_service.py'),
    node('price.formula','定价公式','price','PricingFormula','models/pricing_formula.py'),
    node('campaign.mapping','淘宝商品SKU映射','campaign','TaobaoListing / SkuIdentity','models/taobao_listing.py'),
    node('campaign.window','精确活动窗口与计划','campaign','CampaignPlan','models/campaign.py'),
    node('campaign.files','模板与价格文件','campaign','campaign_workflow_service','services/campaign_workflow_service.py'),
    node('campaign.receipt','官方报名终态','campaign','CampaignSignup','models/campaign_signup.py','', '已成功/未知结果不重传；不把上传成功当报名成功'),
    node('order.file','原报表与批次','order','ImportedFile / ImportJob','models/import_file.py'),
    node('order.parent','母订单','order','Order.order_no','models/order.py','class Order('),
    node('order.child','全部导入子订单','order','OrderDetail.sub_order_no / source','models/order.py','class OrderDetail'),
    node('order.qty','原购买数量','order','OrderDetail.qty','models/order.py','class OrderDetail','原始交易事实，不能被成品数量覆盖'),
    node('order.refund','子单关闭与退款','order','OrderDetail.line_status / refund_status','services/order_line_delivery_service.py'),
    node('order.notes','备注及身份版本','order','Order.buyer_message / remark / seller_memo / production_note','services/factory_production_evidence.py','def _identity'),
    node('order.customer','客户和收货信息','order','Customer / Order.customer_address','models/customer.py'),
    node('quantity.card','数量询问卡','quantity','factory_quantity_request:<line_id>','services/factory_quantity_request_service.py','def request_quantity'),
    node('quantity.reply','真实回复与身份核验','quantity','handle_reply','services/factory_quantity_request_service.py','def handle_reply'),
    node('quantity.physical','确认成品数量','quantity','factory_quantity_confirmation.physical_qty','services/factory_production_evidence.py','def quantity_confirmation','身份或备注变化会使确认失效'),
    node('factory.sheet','正式制单事实与图片','factory','FactorySheet.qty / size_info / materials','services/factory_sheet.py','def build_for_order_line'),
    node('factory.receipt','精确子单图片回执','factory','OrderDetail.factory_delivery_state / factory_delivery_message_id','services/order_line_delivery_service.py'),
    node('factory.archive','不可变已发图片档案','factory','ImportedFile.row_summary.rendered_line','services/order_sheet_archive_service.py','def archive_sent_line_snapshot'),
    node('factory.void','原图作废与更正','factory','order_line_delivery_service','services/order_line_delivery_service.py'),
    node('factory.order','工厂采购/生产单据','factory','FactoryOrder','models/order.py','class FactoryOrder'),
    node('purchase.quote','询价与供应商决策','purchase','ProcurementTask','models/procurement.py'),
    node('purchase.parts','配件采购与到货','purchase','PartPurchase','models/order.py','class PartPurchase'),
    node('purchase.supplier','供应商资料与评分','purchase','Supplier / SupplierScore','models/supplier.py'),
    node('stock.lock','BOM物料占用','stock','InventoryLockLedger','services/inventory_lock_service.py','def lock_for_factory_order'),
    node('stock.consume','发货消耗与释放','stock','consume_for_shipment / release_factory_order_lock','services/inventory_lock_service.py','def consume_for_shipment'),
    node('stock.inbound','入库、退回、拆解','stock','inbound_part / return_in_product / disassemble_product_to_parts','services/inventory_lock_service.py','def inbound_part'),
    node('stock.balance','库存结余与台账','stock','Inventory / InventoryLockLedger','models/inventory.py'),
    node('shipping.tracking','实体物流轨迹','shipping','Shipment.entity_type / entity_id / tracking_no','models/shipment.py'),
    node('shipping.status','有条件的签收派生','shipping','_apply_derivation','services/shipment_service.py','def _apply_derivation'),
    node('shipping.fulfilled','逐产品实际发齐证据','shipping','仓库逐子单履约证据','services/order_line_delivery_service.py','','待接入实发证据；图送达不证明客户收到全部产品'),
    node('after.case','售后记录','after','AfterSales','services/aftersales_auto_service.py'),
    node('after.return','补发与退货单','after','RefillRecord / AfterSales','models/order.py'),
    node('after.payment','退款赔付事实','after','AfterSalesPayment','models/aftersales_payment.py'),
    node('finance.estimate','理论成本估算','finance','Order.theoretical_cost','services/order_cost_service.py','def recompute_and_save'),
    node('finance.actual','实际成本及账单','finance','Order.actual_cost / financial bills','services/order_financials.py','def physical_cost_breakdown'),
    node('finance.profit','利润与期间汇总','finance','net_profit / accounting_summary','services/order_financials.py','def accounting_summary'),
    node('finance.freight','整单运装费用','finance','LogisticsBill / installation bills','models/finance.py'),
    node('settlement.payment','支付流水与月结','settlement','FactorySettlementPayment','services/factory_settlement_service.py','def settle_month'),
    node('settlement.reverse','结算冲销','settlement','reverse_settlement','services/factory_settlement_service.py','def reverse_settlement'),
    node('settlement.period','会计期间与锁定','settlement','AccountingPeriod.status','models/accounting_period.py'),
    node('settlement.expense','工资、押金、期间费用','settlement','staff_salary / shop_deposit','services/staff_salary_service.py'),
    node('marketing.promo','推广、品牌与样品','marketing','Marketing / promotion flows','models/marketing.py'),
    node('marketing.review','评价资产边界','marketing','ReviewAsset','models/review_asset.py','','独立评价程序，不继承ERP生产权限'),
    node('sync.factory','工厂表管理字段','sync','factory_dispatch.build_rows','services/factory_dispatch_feishu_service.py','def build_rows'),
    node('sync.readback','工厂表写后读回','sync','factory_dispatch.sync / preview_diff','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    node('sync.generic','通用表格绑定','sync','FeishuSyncBinding','models/feishu_sync.py','','与专用工厂表单向投影不同'),
    node('sync.manual','工厂手工列','sync','未列入FIELD_SPECS的远程字段','services/factory_dispatch_feishu_service.py','def _business_payload'),
    node('automation.batch','持久批次与文件证据','automation','automation_pipeline_service','services/automation_pipeline_service.py'),
    node('automation.agent','固定Web Agent执行','automation','web_agent_service','services/web_agent_service.py'),
    node('automation.closeout','订单收口与分项结果','automation','complete_recovered_order_delivery','services/order_delivery_completion_service.py','def complete_recovered_order_delivery'),
    node('automation.timer','定时运行记录','automation','ScheduledJobRun','models/scheduled_job.py'),
    node('automation.alert','失败、等待与告警','automation','Alert / DataException','models/alert.py'),
    node('governance.auth','角色与页面权限','governance','User.role / page_perms','dependencies.py','def enforce_page_permission'),
    node('governance.change','字段变更与审计','governance','FieldChange / SystemEvent','models/field_change.py'),
    node('governance.backup','备份与恢复边界','governance','backup_service','services/backup_service.py'),
    node('order.purchase_facts','全部有效购买明细','order','OrderDetail SKU/qty/refund','services/order_purchase_facts.py','def purchase_lines'),
    node('finance.sales_sku','逐SKU销量与未分摊金额','finance','sales product_breakdown','services/sales_analytics.py','def product_breakdown'),
    node('finance.dashboard','月度大盘销售占比','finance','sales_mix','services/dashboard_monthly_service.py','def sales_mix'),
    node('finance.cache','销售缓存与来源指纹','finance','SalesDailyRollup','services/sales_rollup_service.py','def query_summary'),
    node('finance.closeout','限定派生修复与待核实台账','finance','source-bound closeout','services/multi_child_closeout_service.py','def apply'),
    node('stock.demand','逐子SKU需求预测','stock','DemandObservation','services/inventory_demand_service.py','def load_observations'),
]


def edge(a, b, action, condition, check, path, anchor='', kind='data', evidence='code'):
    return {'id': a + '>' + b, 'from': a, 'to': b, 'action': action,
            'condition': condition, 'check': check, 'kind': kind, 'evidence': evidence,
            'sources': [source(path, anchor)]}


EDGES = [
    edge('order.parent','stock.ship_movement','读取母单扣成品现货','有产品/订单ID且原事件尚未记账、有正现货','核对母单qty与全部有效子行；无现货no-op不等于已发齐','services/product_stock_ledger_service.py','def record_shipment'),
    edge('order.child','stock.ship_movement','多子SKU库存覆盖缺口','当前函数读取母单product_code/sku/qty','逐子SKU实际库存扣减未在此入口证明，不能用图或表已同步替代','services/product_stock_ledger_service.py','def record_shipment',kind='gap',evidence='gap'),
    edge('stock.finished','stock.ship_movement','选择可扣现货行','SKU精确匹配优先，否则回退现货最多行','规格回退不等于精确匹配；扣减上限为现存量','services/product_stock_ledger_service.py','def _pick_stock_row',evidence='review'),
    edge('stock.ship_movement','stock.finished','按实际记账take减少现货','唯一reason+entity账本插入成功','take=min(母单qty,现货)；不以本条关系证明客户收到货','services/product_stock_ledger_service.py','def record_shipment'),
    edge('factory.order','stock.restock','区分备货与客户生产单','source_order_id为空且qty为正、原流水不存在','客户MTO到货不自动增加可售现货','services/product_stock_ledger_service.py','def record_restock_receipt'),
    edge('stock.restock','stock.finished','增加成品现货并记入库日期','已插入唯一到货流水','首次备货可能建库存行；不混同物料库存','services/product_stock_ledger_service.py','def record_restock_receipt'),
    edge('stock.ship_movement','stock.reversal','原出库可作为冲正依据','明确调用reverse且能找到原流水','查重、仓库与规格；不能因为图谱提示自动撤销库存','services/product_stock_ledger_service.py','def reverse',kind='protect'),
    edge('stock.reversal','stock.finished','冲正影响现货结余','原库存行存在；现货不低于零','流水冲正量与实际结余变化须对平；不自动复原订单','services/product_stock_ledger_service.py','def reverse',evidence='review'),
    edge('governance.approval','automation.alert','审批待办与状态提醒','create_request建待办；approve/reject处理提示','审批不得自批，非pending不重复批准','services/approval_service.py','def approve'),
    edge('governance.approval','finance.actual','审批状态不是支付凭证','执行器只在action已注册时调用','approved但未注册执行器不证明真实付款；必须核对动作回执','services/approval_service.py','def approve',kind='protect'),
    edge('shipping.confirmed_month','sync.factory','月份说明进入工厂表投影','须另走原同步程序并读回','apply_confirmed_months不发送消息/不同步；月未知日不得造某天','services/factory_shipping_confirmation_service.py','def read_confirmed_months'),
    edge('shipping.confirmed_month','factory.sheet','保留已有生产安排','精确原授权且生命周期无冲突','修改发货月份不取消生产、不重发图、不改其他订单','services/factory_shipping_confirmation_service.py','def apply_confirmed_months',kind='protect'),
    edge('governance.source_index','governance.relationships','扩展变更核查候选范围','反向导入引用有界展开，未识别路径仍输出','代码依赖不是数据传播；缺源码和解析异常不能清零','services/business_relationship_service.py','def review_changes'),
    edge('governance.auth','governance.relationships','复用工具页角色限制','管理员或操作员；仅GET元数据','不读取订单，不调用发送、报名、库存和财务执行器','api/admin.py','def business_relationship_changes',kind='boundary'),
    edge('order.child','order.purchase_facts','读取有效购买行','排除母单汇总/服务/全退，部分退款保留','数量未知不填1；无子行编码不猜','services/order_purchase_facts.py','def _filter_lines'),
    edge('order.purchase_facts','finance.estimate','按全部有效行计算成本','缺价/数量或护栏失败','保留原估值并待核实，不回退首SKU','services/order_cost_service.py','def recompute_and_save'),
    edge('order.purchase_facts','finance.sales_sku','逐子SKU统计购买件数','同一母单现金仅一次','未分摊金额单列；子单待分摊不是零售价','services/order_purchase_facts.py','def sales_projections'),
    edge('finance.sales_sku','finance.dashboard','保持金额守恒与子单数量','月度实时数据','入户玄关柜不是服务；真实账单不改','services/dashboard_monthly_service.py','def sales_mix'),
    edge('order.purchase_facts','finance.cache','刷新可再生销售缓存','订单/子单来源指纹一致','过期返回实时查询；毛估利润不是会计净利','services/sales_rollup_service.py','def _source_fingerprints'),
    edge('order.purchase_facts','stock.demand','逐子SKU进入预测与未发需求','保留已有预测清洗政策','不复制母单金额到每个子SKU；未知状态不判已发','services/inventory_demand_service.py','def current_unshipped_standard_qty'),
    edge('order.child','sync.readback','检查全量实体覆盖','旧汇总只做历史保留；旧记录唯一绑定','未匹配子单不能宣称同步成功','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    edge('finance.estimate','finance.closeout','源文件与完整SKU核对后修派生值','只处理可证明分项；关账期间不改','实际付款/账单保护；未决写异常台账','services/order_completeness_incident.py','def all_product_financial_plan'),
    edge('finance.closeout','finance.cache','一次重建当前年派生缓存','精确计划hash、事务锁及防重复回执','不重新导单/发图/修改真实账单','services/multi_child_closeout_service.py','def apply'),
    edge('npd.project','npd.gate','阶段门检查','切换阶段时','未完成必做任务/检验不得混同已通过','services/npd_service.py','def move_project'),
    edge('npd.gate','npd.materialize','核对建档资格','操作员请求建档；具体门分支须复核','阶段切换不等于自动正式化','services/npd_service.py','def materialize_project',evidence='review'),
    edge('npd.materialize','product.identity','生成正式商品','有BOM且未曾建档','重复建档拒绝','services/npd_service.py','def materialize_project'),
    edge('npd.materialize','bom.lines','生成正式BOM','明确建档动作','物料编码、数量、单价逐项核对','services/npd_service.py','def materialize_project'),
    edge('npd.materialize','price.current','生成草稿定价','建档成功','草稿不是已批准渠道售价','services/npd_service.py','def materialize_project'),
    edge('product.identity','product.sku','产品-规格关联','精确product_code','多规格不得合并','models/pricing.py'),
    edge('product.sku','product.dimensions','选择精确尺寸','同SKU及验证hash','不得使用其他变体图','services/factory_production_evidence.py','def verified_dimensions'),
    edge('product.custom','factory.sheet','定制尺寸优先','精确变体存在','缺尺寸保留待核实','services/factory_sheet.py','def build_from_fields'),
    edge('bom.material','bom.drift','触发成本核对','物料变更且SKU使用此物料','只核相关SKU，不改售价','services/pricing_bom_sync_service.py','def check_for_material'),
    edge('bom.lines','bom.drift','计算BOM成本差异','有可计算的物料价格','空价格不当零','services/pricing_bom_sync_service.py','def check_sku'),
    edge('bom.drift','price.current','禁止自动改售价','成本漂移只产生提示','售价仍由原定价流程决定','services/pricing_bom_sync_service.py',kind='protect'),
    edge('price.formula','price.current','派生价格字段','显式重算入口','日常/中促/大促口径不能互换','services/pricing_calc_service.py'),
    edge('price.current','price.version','保存价格版本','版本服务入口','历史版本边界需核对','services/pricing_version_service.py',evidence='review'),
    edge('price.version','finance.estimate','按订单日期取价','历史快照存在','不得用现价覆盖历史依据','services/order_cost_service.py','def _asof_pricing'),
    edge('product.sku','campaign.mapping','规格身份映射','ERP编码与平台SKU唯一','缺失不猜映射','models/sku_identity.py'),
    edge('campaign.mapping','campaign.files','选择报名范围','ERP可售∩淘宝上架','排除无对应仅限本场文件','services/campaign_workflow_service.py',evidence='review'),
    edge('price.current','campaign.files','填价格与优惠','同价版本/精确窗口','普通报名价=日常价；容差不逐轮累计','services/campaign_workflow_service.py',evidence='review'),
    edge('campaign.window','campaign.files','绑定模板与窗口','当次官方身份','不复用旧已填数据','services/campaign_workflow_service.py',evidence='review'),
    edge('campaign.files','campaign.receipt','固定程序提交并取终态','一次claim且非成功/未知','上传成功不是报名成功','services/campaign_workflow_service.py',evidence='review'),
    edge('order.file','order.parent','导入母单字段','原始导入档案','缺列不清空现有事实','services/taobao_order_import.py'),
    edge('order.parent','order.child','关联全部购买行','存在source=import','不得只取第一件；全过滤后不退回母单','services/order_line_delivery_service.py'),
    edge('order.child','order.qty','保留逐子单购买数','原始购买明细','缺失/0不是1','models/order.py','class OrderDetail'),
    edge('order.qty','quantity.card','需要时询问成品数','未知购买数或定制多计价单位','普通有效数量不强制询问','services/factory_quantity_request_service.py','def request_quantity'),
    edge('quantity.card','quantity.reply','等待真人回复','回复对应卡且来自正确群','群里孤立数字不能确认','services/factory_quantity_request_service.py','def handle_reply'),
    edge('quantity.reply','quantity.physical','记录确认依据','真实消息读回且身份未变化','确认人/回复/精确子单齐全，冲突不覆盖','services/factory_production_evidence.py','def confirm_quantity'),
    edge('order.notes','quantity.physical','使旧确认失效','备注/购买数/SKU身份发生变化','不能沿用旧卡默认为已确认','services/factory_production_evidence.py','def _identity'),
    edge('quantity.physical','factory.sheet','取成品量制单','确认记录与当前身份相符','购买量仍原值；材料按成品量','services/factory_sheet.py','def build_for_order_line'),
    edge('order.qty','factory.sheet','普通购买数作为成品数','有效数量且无定制计价歧义','0/空/负数必须待确认','services/factory_sheet.py','def build_for_order_line'),
    edge('product.dimensions','factory.sheet','读取精确尺寸','SKU/产品/hash一致','错变体和过期hash不通过','services/factory_sheet.py','def build_from_fields'),
    edge('bom.lines','factory.sheet','生成物料需求','BOM×确认成品数','未知数不能作为正式生产单','services/factory_sheet.py','def build_from_fields'),
    edge('order.customer','factory.sheet','收货信息和备注','地址未脱敏或明确待补分支','信息待补不捏造地址','services/factory_sheet.py','def build_for_order_line'),
    edge('factory.sheet','factory.receipt','固定逐子单发送','生产事实合格且未送达/未占用','未知发送不盲重试','services/order_sheet_archive_service.py'),
    edge('factory.receipt','factory.archive','存已发内容快照','真实图片message_id','按SKU/数量/hash审计，不用母单sent替代','services/order_sheet_archive_service.py','def archive_sent_line_snapshot'),
    edge('order.refund','factory.void','确定作废或停用范围','精确子单关闭/退款','不得作废有效兄弟单','services/order_line_delivery_service.py'),
    edge('quantity.physical','order.qty','禁止覆盖原购买量','数量确认仅供生产','交易数量保持不变','services/factory_production_evidence.py','def confirm_quantity',kind='protect'),
    edge('quantity.physical','finance.actual','禁止修改实际账单','成品数确认','不得自动改实付/已结账金额','services/factory_production_evidence.py','def confirm_quantity',kind='protect'),
    edge('order.child','finance.estimate','汇总全部有效产品成本','排除退款/非实体行','同SKU多件也要累计','services/order_cost_service.py','def _multi_product_cost'),
    edge('finance.estimate','finance.actual','禁止估算覆盖实账','recompute_and_save','actual_cost不清空或重写','services/order_cost_service.py','def recompute_and_save',kind='protect'),
    edge('finance.estimate','finance.profit','缺实际时的估算口径','遵守成本优先级','展示估算/实账差异','services/order_financials.py','def cost_breakdown'),
    edge('finance.actual','finance.profit','汇总真实分项成本','账单匹配及口径正确','木作不等于全部成本','services/order_financials.py','def physical_cost_breakdown'),
    edge('finance.freight','finance.profit','计入整单费用','费用已匹配','不擅自均摊到每个子SKU','services/order_financials.py','def cost_breakdown'),
    edge('factory.order','stock.lock','生成物料占用','工厂单发起锁库','锁库不代表消耗','services/inventory_lock_service.py','def lock_for_factory_order'),
    edge('bom.lines','stock.lock','BOM决定占用量','精确SKU/工厂单','单位、数量、锁库身份一致','services/inventory_lock_service.py','def lock_for_factory_order'),
    edge('stock.lock','stock.consume','发货消耗/取消释放','不同明确动作','释放和消耗不得重复执行','services/inventory_lock_service.py','def consume_for_shipment'),
    edge('stock.consume','stock.balance','更新库存台账','合法流水','结余与流水一致','services/inventory_lock_service.py','def consume_for_shipment'),
    edge('purchase.quote','purchase.parts','采购决策后建单','原采购流程','询价不等于授权下单','services/procurement_service.py',evidence='review'),
    edge('purchase.supplier','purchase.quote','供应商关联','候选与选定区分','不自动付款','services/procurement_service.py',evidence='review'),
    edge('purchase.parts','stock.inbound','采购到货入库','入库动作','到货不能重复增加库存','services/inventory_lock_service.py','def inbound_part'),
    edge('stock.inbound','stock.balance','写入库存流水','入库/退回/拆解各自身份','撤销必须关联原流水','services/inventory_lock_service.py','def return_in_product'),
    edge('shipping.tracking','shipping.status','同步轨迹派生状态','entity_type限定','同运单不同实体不得错绑','services/shipment_service.py','def _apply_derivation'),
    edge('shipping.status','shipping.fulfilled','需要逐项实发核验','仅包裹签收不能证明全商品发齐','核对每个子单实发数量/包裹内容','services/shipment_service.py',kind='gap',evidence='gap'),
    edge('factory.receipt','shipping.fulfilled','禁止把发图当发货','两种外部事实不同','仓库和客户履约回执独立','services/order_line_delivery_service.py',kind='protect'),
    edge('order.refund','after.case','创建售后记录','退款同步条件满足','生成记录不等于退款或补发完成','services/aftersales_auto_service.py'),
    edge('after.case','after.return','售后处理与补件','人工确认补发/退货','不得变成重复原单生产','models/order.py',evidence='review'),
    edge('after.return','stock.inbound','退回二次入库','签收且入库确认','物流签收和库存记账分开','services/inventory_lock_service.py','def return_in_product'),
    edge('after.payment','finance.profit','售后费用归集','真实赔付记录','不由图触发支付','services/order_financials.py','def extra_aftersales'),
    edge('settlement.payment','settlement.reverse','按原支付记录冲销','明确反结算动作','不删除真实交易事实','services/factory_settlement_service.py','def reverse_settlement'),
    edge('settlement.period','finance.profit','期间口径','月/期间边界','锁定期间不能因结构分析重算','services/accounting_period_service.py',evidence='review'),
    edge('settlement.expense','finance.profit','期间费用归集','费用类型和日期','未分配费用不编造单件成本','services/order_financials.py','def accounting_summary',evidence='review'),
    edge('marketing.promo','finance.profit','推广期间费用','费用确认和日期范围','推广充值与实际消耗不同','services/order_financials.py','def accounting_summary',evidence='review'),
    edge('marketing.review','order.child','外部评价边界','只在批准数据合同内关联','不自动抓取客户/执行评价','models/review_asset.py',kind='boundary',evidence='review'),
    edge('factory.sheet','sync.factory','复用生产事实投影','每个有效子单','成品数、购买数、尺寸和确认状态一致','services/factory_dispatch_feishu_service.py','def build_rows'),
    edge('order.refund','sync.factory','有效生产范围核对','精确子单关闭/退款','不连带删除兄弟单','services/factory_dispatch_feishu_service.py','def _line_void'),
    edge('factory.receipt','sync.factory','已发图附件绑定','编号/图片签名相符','不以任意最新图冒充正式已发图','services/factory_dispatch_feishu_service.py','def build_rows'),
    edge('sync.factory','sync.readback','增量投影并读回','单写锁且原自动同步启用','写入回执与字段一致各自检查','services/factory_dispatch_feishu_service.py','def _sync_unlocked'),
    edge('sync.factory','sync.manual','禁止覆盖工厂手工列','只允许FIELD_SPECS字段','未管理列保持原样','services/factory_dispatch_feishu_service.py','def _business_payload',kind='protect'),
    edge('sync.generic','sync.factory','两类表同步不等价','专用表单向/通用表按绑定','不得继承通用双向写回规则','models/feishu_sync.py',kind='boundary'),
    edge('quantity.reply','sync.readback','更新确认后的工厂投影','图回执独立；表失败保留','不能因表失败重发正式图','services/factory_quantity_request_service.py','def handle_reply'),
    edge('automation.batch','automation.agent','交给固定程序执行','一次持久批次','AI不逐步操控浏览器','services/web_agent_service.py',evidence='review'),
    edge('automation.agent','order.file','取回报表证据','batch/attempt/hash匹配','超时结果未知不重复拉取','services/web_agent_service.py',evidence='review'),
    edge('automation.batch','automation.closeout','恢复已导入批次','身份与日期一致','历史批次不改当天状态','services/order_delivery_completion_service.py'),
    edge('automation.closeout','factory.receipt','完成待发图片','精确发送账本保护','已送达/未知不重放','services/order_delivery_completion_service.py'),
    edge('automation.closeout','sync.readback','独立工厂投影收口','图失败不吞掉表结果','表关闭不称已同步；整体错误保留','services/order_delivery_completion_service.py'),
    edge('automation.timer','automation.batch','定时调度批次','原调度设置启用','不增加AI监工定时','services/scheduler.py',evidence='review'),
    edge('automation.closeout','automation.alert','记录失败及等待','分项结果明确','未知/待人工不能涂绿','services/order_delivery_completion_service.py'),
    edge('governance.auth','automation.batch','访问与动作边界','既有角色/页面权限','图不扩张业务权限','dependencies.py','def require_role',kind='boundary'),
    edge('governance.change','sync.generic','保留字段来源和变更','原同步入口','变更记录不等于外部已更新','services/feishu_sync_service.py',evidence='review'),
    edge('governance.backup','factory.receipt','恢复不授权重放发送','恢复数据库后','必须重新对账消息/发送账本','services/backup_service.py',kind='protect'),
    edge('quantity.physical','stock.lock','成品数量变化需核对用料','物料占用是否已按新成品数更新待验证','只提醒核对，不自动改库存台账','services/inventory_lock_service.py',kind='gap',evidence='gap'),
]

FLOWS = [
    {'id':'finished-stock','name':'成品现货 → 母单扣库/备货入库 → 冲正与子SKU覆盖核查',
     'steps':['order.parent','order.child','stock.finished','stock.ship_movement','factory.order','stock.restock','stock.reversal','shipping.fulfilled']},
    {'id':'approval','name':'人工审批 → 注册执行器 → 独立结果与告警核对',
     'steps':['governance.auth','governance.approval','automation.alert','finance.actual','governance.change']},
    {'id':'maintenance','name':'程序变更 → 依赖候选 → 业务影响与保护检查',
     'steps':['governance.auth','governance.source_index','governance.relationships','governance.change','governance.backup']},
    {'id':'automation','name':'定时与文件 → 固定程序 → 分项收口与告警',
     'steps':['automation.timer','automation.batch','automation.agent','order.file','automation.closeout','factory.receipt','sync.readback','automation.alert']},
    {'id':'sync','name':'数量/制单事实 → 工厂表 → 独立读回与手工字段保护',
     'steps':['quantity.reply','factory.sheet','factory.receipt','sync.factory','sync.readback','sync.manual','sync.generic']},
    {'id':'after','name':'子单退款 → 售后 → 退回入库与费用核对',
     'steps':['order.refund','after.case','after.return','stock.inbound','after.payment','finance.profit']},
    {'id':'settlement','name':'实际账单 → 月结支付 → 冲销与会计期间',
     'steps':['finance.actual','finance.freight','finance.profit','settlement.payment','settlement.reverse','settlement.period','settlement.expense']},
    {'id':'marketing','name':'推广样品与评价 → 费用/订单及系统权限边界',
     'steps':['marketing.promo','marketing.review','order.child','finance.profit','governance.auth']},
    {'id':'reporting','name':'全部子单 → 销量 → 财务及大盘 → 缓存核验',
     'steps':['order.child','order.purchase_facts','finance.estimate','finance.sales_sku','finance.dashboard','finance.cache','stock.demand']},
    {'id':'order','name':'订单 → 数量确认 → 制单 → 工厂表',
     'steps':['order.file','order.child','order.qty','quantity.card','quantity.reply','quantity.physical','factory.sheet','factory.receipt','sync.factory','sync.readback']},
    {'id':'product','name':'研发 → 商品 → BOM → 定价',
     'steps':['npd.project','npd.gate','npd.materialize','product.identity','product.sku','bom.lines','bom.drift','price.current']},
    {'id':'campaign','name':'价格与映射 → 活动 → 官方结果',
     'steps':['price.current','campaign.mapping','campaign.window','campaign.files','campaign.receipt']},
    {'id':'fulfillment','name':'采购生产 → 库存 → 物流 → 售后',
     'steps':['purchase.quote','purchase.parts','factory.order','stock.lock','stock.consume','stock.balance','shipping.tracking','shipping.status','shipping.fulfilled','after.case','after.return']},
    {'id':'finance','name':'购买行与历史价 → 成本 → 财务结算',
     'steps':['order.child','price.version','finance.estimate','finance.actual','finance.freight','after.payment','finance.profit','settlement.payment','settlement.period']},
]
