"""Excel importer 的目标 schema 定义.

每个 entity 描述: 目标字段集 + 字段类型 + 是否必填 + 别名提示 (给 AI 推断用)。
新增 entity 只需在这里加一项, importer / API / 前端会自动支持。
"""
from __future__ import annotations

from typing import Literal, TypedDict


FieldType = Literal["str", "int", "decimal", "date", "datetime", "bool"]


class FieldDef(TypedDict, total=False):
    type: FieldType
    required: bool
    desc: str
    aliases: list[str]  # 给 AI 提示: "这个字段在 Excel 里常见的列名"


class EntitySchema(TypedDict):
    label: str
    description: str
    fields: dict[str, FieldDef]
    group_by: list[str]   # 同一组的行合并为一个父对象 (如 同 note_no → 一张 DeliveryNote)
    parent_fields: list[str]  # 这些字段属于父对象, 其他属于明细行


ENTITY_SCHEMAS: dict[str, EntitySchema] = {
    "product": {
        "label": "产品总表",
        "description": "每行 = 一个产品 (Product). 同 code 已存在会更新. "
                       "若行内含 sku_code 则同步写入 pricing_sku.",
        "fields": {
            "code": {"type": "str", "required": True, "desc": "产品编码",
                     "aliases": ["产品编码", "产品 code", "ProductCode", "SPU 编码"]},
            "name": {"type": "str", "required": True, "desc": "产品名称 (含竖线分隔符时自动拆副名称)",
                     "aliases": ["产品名称", "产品名", "Name", "商品名"]},
            "category": {"type": "str", "required": False, "desc": "类目",
                         "aliases": ["类目", "分类", "Category"]},
            "brand": {"type": "str", "required": False, "desc": "品牌",
                      "aliases": ["品牌", "Brand"]},
            "listing_status": {"type": "str", "required": False, "desc": "上架状态",
                                "aliases": ["上架状态", "状态", "在售状态"]},
            "main_material": {"type": "str", "required": False, "desc": "主材介绍",
                               "aliases": ["主材介绍", "主材", "主要材料"]},
            "image_url": {"type": "str", "required": False, "desc": "图片链接",
                          "aliases": ["图片链接", "图片", "图片URL", "主图链接"]},
            "custom_scope": {"type": "str", "required": False, "desc": "定制范围",
                             "aliases": ["定制范围"]},
            "size_detail": {"type": "str", "required": False, "desc": "尺寸明细",
                            "aliases": ["尺寸明细", "尺寸"]},
            "size_value": {"type": "str", "required": False, "desc": "尺寸值(mm), 空→'待定'",
                           "aliases": ["尺寸值", "尺寸值(mm)", "尺寸 mm"]},
            "size_confirmed": {"type": "str", "required": False, "desc": "尺寸是否确定, 空→'待确定'",
                               "aliases": ["尺寸是否确定", "是否确定尺寸"]},
            "aux_material": {"type": "str", "required": False, "desc": "辅材介绍",
                             "aliases": ["辅材介绍", "辅材"]},
            "accessory_desc": {"type": "str", "required": False, "desc": "外配件说明, 空→'-'",
                                "aliases": ["外配件说明", "配件说明", "外配件"]},
            "accessory_remark": {"type": "str", "required": False, "desc": "配件备注, 空→'-'",
                                  "aliases": ["配件备注", "外配备注"]},
            "description": {"type": "str", "required": False, "desc": "产品文案",
                            "aliases": ["产品文案介绍", "产品文案", "文案介绍", "文案"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "Remark"]},
            "taobao_id": {"type": "str", "required": False, "desc": "淘宝商品 ID",
                          "aliases": ["淘宝 ID", "淘宝商品 ID", "TaobaoID"]},
            "taobao_sku_id": {"type": "str", "required": False, "desc": "淘宝 SKU ID, 空→'待定'",
                               "aliases": ["淘宝SKU ID", "淘宝 SKU ID", "TaobaoSkuID"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格描述"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU 编码 (同步写 pricing_sku)",
                         "aliases": ["SKU编码", "SKU code", "sku_code"]},
        },
        "group_by": ["code"], "parent_fields": [],
    },
    "material": {
        "label": "物料 / 配件价格",
        "description": "每行 = 一个物料 (Material).",
        "fields": {
            "code": {"type": "str", "required": True, "desc": "物料编码",
                     "aliases": ["物料编码", "配件编码", "Code"]},
            "name": {"type": "str", "required": True, "desc": "物料名称",
                     "aliases": ["物料名称", "配件名称", "名称", "Name"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位", "Unit"]},
            "size_type": {"type": "str", "required": False, "desc": "尺寸类型 (组合/个数)",
                          "aliases": ["尺寸类型"]},
            "price": {"type": "decimal", "required": False, "desc": "单价",
                      "aliases": ["计算价格", "单价", "Price"]},
            "lead_time_days": {"type": "int", "required": False, "desc": "补货周期天数",
                               "aliases": ["补货周期", "lead time", "LeadTime"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "Remark"]},
        },
        "group_by": ["code"], "parent_fields": [],
    },
    "bom_line": {
        "label": "BOM 物料分解",
        "description": "每行 = 一条 BOM (产品+SKU+物料+用量).",
        "fields": {
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码", "产品 code"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU 编码",
                         "aliases": ["SKU编码", "SKU code"]},
            "material_code": {"type": "str", "required": True, "desc": "物料编码",
                              "aliases": ["物料编码", "配件编码"]},
            "qty_per_product": {"type": "decimal", "required": True, "desc": "单产品用量",
                                "aliases": ["单产品用量", "用量", "数量", "Qty"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位", "Unit"]},
            "size_type": {"type": "str", "required": False, "desc": "尺寸类型",
                          "aliases": ["尺寸类型"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称 (冗余备查)",
                             "aliases": ["产品名称", "产品名"]},
            "material_name": {"type": "str", "required": False, "desc": "物料名称 (冗余备查)",
                              "aliases": ["物料名称", "配件名称", "物料名"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "product_inventory": {
        "label": "成品库存",
        "description": "每行 = 一条成品库存 (按 仓库+产品+SKU 唯一).",
        "fields": {
            "warehouse": {"type": "str", "required": False, "desc": "仓库 (默认 江西仓库)",
                          "aliases": ["仓库", "仓库名称"]},
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "sku": {"type": "str", "required": False, "desc": "SKU",
                    "aliases": ["SKU", "规格"]},
            "spec": {"type": "str", "required": False, "desc": "规格尺寸",
                     "aliases": ["规格尺寸", "规格"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位"]},
            "physical_qty": {"type": "decimal", "required": False, "desc": "物理库存",
                             "aliases": ["物理库存", "实物库存", "库存"]},
            "locked_qty": {"type": "decimal", "required": False, "desc": "锁定库存",
                           "aliases": ["锁定库存", "已锁"]},
            "safety_stock": {"type": "decimal", "required": False, "desc": "安全库存",
                             "aliases": ["安全库存预警线", "安全库存"]},
            "lead_time_days": {"type": "int", "required": False, "desc": "提前期(天)",
                               "aliases": ["提前期", "补货周期", "采购提前期"]},
            "slow_moving_days": {"type": "int", "required": False, "desc": "滞销预警天数",
                                 "aliases": ["滞销预警天数", "滞销天数"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "part_inventory": {
        "label": "配件库存",
        "description": "每行 = 一条配件库存 (按 仓库+物料 唯一).",
        "fields": {
            "warehouse": {"type": "str", "required": False, "desc": "仓库",
                          "aliases": ["仓库", "仓库名称"]},
            "material_code": {"type": "str", "required": False, "desc": "物料编码 (空时按名称自动匹配或生成临时编码)",
                              "aliases": ["物料编码", "配件编码"]},
            "material_name": {"type": "str", "required": False, "desc": "物料名称 (配件编码为空时用于反查/生成临时编码)",
                              "aliases": ["物料名称", "配件名称", "品名", "商品名"]},
            "spec": {"type": "str", "required": False, "desc": "规格型号",
                     "aliases": ["规格型号", "规格"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位"]},
            "physical_qty": {"type": "decimal", "required": False, "desc": "物理库存",
                             "aliases": ["物理库存", "库存"]},
            "locked_qty": {"type": "decimal", "required": False, "desc": "锁定库存",
                           "aliases": ["锁定库存"]},
            "safety_stock": {"type": "decimal", "required": False, "desc": "安全库存",
                             "aliases": ["安全库存预警线", "安全库存"]},
            "last_inbound_at": {"type": "date", "required": False, "desc": "最后入库日期",
                                "aliases": ["最后入库日期", "最近入库日期"]},
            "last_outbound_at": {"type": "date", "required": False, "desc": "最后出库日期",
                                 "aliases": ["最后出库日期", "最近出库日期"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "order": {
        "label": "订单总表",
        "description": "每行 = 一张平台订单 (Order).",
        "fields": {
            "platform": {"type": "str", "required": False, "desc": "平台 (淘宝/抖音/京东等)",
                         "aliases": ["平台", "Platform"]},
            "order_no": {"type": "str", "required": True, "desc": "订单号 (唯一)",
                         "aliases": ["订单编号", "订单号", "OrderNo"]},
            "order_date": {"type": "date", "required": False, "desc": "下单日期",
                           "aliases": ["下单日期", "订单日期"]},
            "ship_date": {"type": "date", "required": False, "desc": "发货日期",
                          "aliases": ["发货日期"]},
            "customer_name": {"type": "str", "required": False, "desc": "客户姓名",
                              "aliases": ["客户姓名", "买家"]},
            "customer_phone": {"type": "str", "required": False, "desc": "电话",
                               "aliases": ["联系电话", "电话", "手机"]},
            "customer_address": {"type": "str", "required": False, "desc": "地址",
                                 "aliases": ["收货地址", "地址"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码", "货号"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名",
                             "aliases": ["产品名称", "商品名"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU 编码",
                         "aliases": ["SKU编码", "SKU code"]},
            "qty": {"type": "int", "required": False, "desc": "数量",
                    "aliases": ["数量", "件数"]},
            "paid_amount": {"type": "decimal", "required": False, "desc": "实付金额",
                            "aliases": ["实付金额", "实付", "付款金额", "买家实付金额"]},
            "discount": {"type": "decimal", "required": False, "desc": "优惠金额",
                         "aliases": ["优惠金额", "折扣金额", "优惠"]},
            "platform_fee": {"type": "decimal", "required": False, "desc": "平台服务费",
                             "aliases": ["平台服务费", "佣金"]},
            "carrier": {"type": "str", "required": False, "desc": "快递公司",
                        "aliases": ["快递公司", "物流公司", "承运商"]},
            "tracking_no": {"type": "str", "required": False, "desc": "快递单号",
                            "aliases": ["快递单号", "物流单号", "快递号"]},
            "theoretical_cost": {"type": "decimal", "required": False, "desc": "产品理论成本",
                                 "aliases": ["产品理论成本", "理论成本"]},
            "actual_cost": {"type": "decimal", "required": False, "desc": "产品实际成本",
                            "aliases": ["产品实际成本", "实际成本"]},
            "actual_freight": {"type": "decimal", "required": False, "desc": "实际运费",
                               "aliases": ["实际运费", "运费"]},
            "is_custom": {"type": "bool", "required": False, "desc": "是否定制",
                          "aliases": ["是否定制", "是否微定制", "定制"]},
            "is_refill": {"type": "bool", "required": False, "desc": "是否补单 (=是时自动与补单记录交叉核验)",
                          "aliases": ["是否补单", "补单", "is_refill"]},
            "warehouse": {"type": "str", "required": False,
                          "desc": "发货仓库 (留空: 样块/补单→杭州, 其余→江西仓库)",
                          "aliases": ["发货仓库", "仓库", "warehouse"]},
            "status": {"type": "str", "required": False, "desc": "订单状态",
                       "aliases": ["订单状态", "状态"]},
            "install_ticket_no": {"type": "str", "required": False, "desc": "安装工单号",
                                  "aliases": ["安装工单号", "安装单号", "工单号"]},
            "upstairs_fee": {"type": "decimal", "required": False, "desc": "上楼费",
                             "aliases": ["上楼费", "搬楼费"]},
            "install_fee": {"type": "decimal", "required": False, "desc": "安装费",
                            "aliases": ["安装费", "安装费用"]},
            "compensation_fee": {"type": "decimal", "required": False, "desc": "订单赔付费",
                                 "aliases": ["订单赔付费", "赔付费", "赔付金额"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            # ── 订单 P&L 扩展 (migration 0046) ──
            "buyer_payable_amount": {"type": "decimal", "required": False, "desc": "买家应付金额",
                                     "aliases": ["买家应付金额", "买家应付", "应付金额"]},
            "shop_received_amount": {"type": "decimal", "required": False, "desc": "店铺实收金额",
                                     "aliases": ["店铺实收金额", "店铺实收", "实收金额"]},
            "tax": {"type": "decimal", "required": False, "desc": "税费",
                    "aliases": ["税费", "税"]},
            "other_fee": {"type": "decimal", "required": False, "desc": "其它费用",
                          "aliases": ["其它费用", "其他费用"]},
            "total_cost": {"type": "decimal", "required": False, "desc": "总成本",
                           "aliases": ["总成本"]},
            "good_review_refund": {"type": "decimal", "required": False, "desc": "好评/差价返",
                                   "aliases": ["好评/差价返", "好评差价返", "好评返", "差价返"]},
            "second_visit_fee": {"type": "decimal", "required": False, "desc": "二次上门维修费",
                                 "aliases": ["二次上门维修费", "二次维修费"]},
            "return_pack_freight": {"type": "decimal", "required": False, "desc": "返厂打包运费",
                                    "aliases": ["返厂打包运费", "返厂运费"]},
            "factory_compensation": {"type": "decimal", "required": False, "desc": "工厂补偿",
                                     "aliases": ["工厂补偿", "工厂补偿金额"]},
            "logistics_compensation": {"type": "decimal", "required": False, "desc": "物流补偿",
                                       "aliases": ["物流补偿", "物流补偿金额"]},
            "compensation_total": {"type": "decimal", "required": False, "desc": "补偿总金额",
                                   "aliases": ["补偿总金额", "补偿合计"]},
            "refund_status": {"type": "str", "required": False, "desc": "退款状态",
                              "aliases": ["退款状态"]},
            "refund_amount": {"type": "decimal", "required": False, "desc": "退款金额",
                              "aliases": ["退款金额"]},
            "refund_date": {"type": "date", "required": False, "desc": "退款日期",
                            "aliases": ["退款日期"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": ["order_no"], "parent_fields": [],
    },
    "account_balance": {
        "label": "账户月度余额",
        "description": "每行 = 一个账户某月的开/收/支/期末.",
        "fields": {
            "account_name": {"type": "str", "required": True, "desc": "账户名",
                             "aliases": ["账户名称", "账户", "账户名"]},
            "year": {"type": "int", "required": False, "desc": "年",
                     "aliases": ["年", "年份", "Year"]},
            "month": {"type": "int", "required": False, "desc": "月",
                      "aliases": ["月", "月份", "Month"]},
            "period_date": {"type": "date", "required": False, "desc": "统计日期 (可代替年+月)",
                            "aliases": ["统计日期", "日期", "Date"]},
            "opening_balance": {"type": "decimal", "required": False, "desc": "期初余额",
                                "aliases": ["期初余额", "期初"]},
            "income": {"type": "decimal", "required": False, "desc": "本月收入",
                       "aliases": ["本月收入", "收入", "收"]},
            "expense": {"type": "decimal", "required": False, "desc": "本月支出",
                        "aliases": ["本月支出", "支出", "支"]},
            "closing_balance": {"type": "decimal", "required": False, "desc": "期末余额",
                                "aliases": ["期末余额", "期末"]},
            "account_no": {"type": "str", "required": False, "desc": "账户号",
                           "aliases": ["账户号", "账号", "账户账号"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "Remark"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "pricing_sku": {
        "label": "定价总表 (SKU 全列)",
        "description": "每行 = 一个 SKU 的完整定价快照，涵盖售价/成本/配件/平台活动价全部列。",
        "fields": {
            # ── 基础标识 ──────────────────────────────────────────────
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称",
                             "aliases": ["产品名称", "品名"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": True, "desc": "SKU 编码 (唯一)",
                         "aliases": ["SKU编码", "SKU code"]},
            "size_category": {"type": "str", "required": False, "desc": "大小分类 (小型/中型/大型)",
                              "aliases": ["大小分类", "尺寸分类", "产品大小类型", "大小类型", "Size"]},
            "image_url": {"type": "str", "required": False, "desc": "图片链接",
                          "aliases": ["图片链接", "图片", "图片URL", "主图链接"]},
            # ── 售价四档 ─────────────────────────────────────────────
            "list_price": {"type": "decimal", "required": False, "desc": "标价 (公式: 物理总成本/0.4)",
                           "aliases": ["标价", "标价计算", "List"]},
            "daily_price": {"type": "decimal", "required": False, "desc": "日常价 / 单品宝 (公式: 标价×0.75)",
                            "aliases": ["日常价/单品宝", "日常价", "日常", "单品宝"]},
            "small_promo": {"type": "decimal", "required": False, "desc": "小促价 (超级立减)",
                            "aliases": ["小促价（超级立减）", "小促价", "小促", "超级立减", "立减价"]},
            "mid_promo": {"type": "decimal", "required": False, "desc": "中促价 (88 券)",
                          "aliases": ["中促价（88券活动）", "中促价", "中促", "88券", "88 券"]},
            "big_promo": {"type": "decimal", "required": False, "desc": "大促价 (双11)",
                          "aliases": ["大促到手价（双11）", "大促价", "大促", "双11", "双 11"]},
            # ── 利润指标 ─────────────────────────────────────────────
            "gross_margin_rate": {"type": "decimal", "required": False, "desc": "即时毛利率 (公式自动算)",
                                  "aliases": ["毛利率", "即时毛利率"]},
            "big_promo_margin": {"type": "decimal", "required": False, "desc": "大促利润 (公式自动算)",
                                 "aliases": ["大促利润", "利润"]},
            # ── 成本拆分 ─────────────────────────────────────────────
            "accounting_cost": {"type": "decimal", "required": False, "desc": "会计总成本",
                                "aliases": ["会计总成本", "总成本", "成本"]},
            "physical_cost": {"type": "decimal", "required": False, "desc": "物理总成本",
                              "aliases": ["物理总成本", "物理成本"]},
            "platform_fee_rate": {"type": "decimal", "required": False, "desc": "平台费率",
                                  "aliases": ["平台费率", "佣金率"]},
            "tax": {"type": "decimal", "required": False, "desc": "税费金额",
                    "aliases": ["税", "税费"]},
            "logistics_cost": {"type": "decimal", "required": False, "desc": "物流费用 (公式按大小分类自动算)",
                               "aliases": ["物流费用", "物流成本", "快递费"]},
            "install_cost": {"type": "decimal", "required": False, "desc": "安装费",
                             "aliases": ["安装费", "安装费用", "安装成本"]},
            "factory_cost": {"type": "decimal", "required": False, "desc": "总出厂成本",
                             "aliases": ["总出厂成本", "出厂成本", "工厂成本"]},
            "wood_cost": {"type": "decimal", "required": False, "desc": "木作成本",
                          "aliases": ["木作成本", "木材成本"]},
            "packaging_cost": {"type": "decimal", "required": False, "desc": "包装成本",
                               "aliases": ["包装成本", "打包", "包材成本"]},
            "external_parts_cost": {"type": "decimal", "required": False, "desc": "外采配件成本合计 (公式: SUM 22项)",
                                    "aliases": ["外采配件成本", "外配件成本", "配件成本合计"]},
            # ── 22 项配件成本明细 (→ pricing_sku_costs) ──────────────
            "rock_slab": {"type": "decimal", "required": False, "desc": "岩板成本",
                          "aliases": ["岩板", "岩板成本"]},
            "drawer_rail": {"type": "decimal", "required": False, "desc": "抽屉轨道成本",
                            "aliases": ["抽屉轨道", "轨道"]},
            "led_strip": {"type": "decimal", "required": False, "desc": "灯带成本",
                          "aliases": ["灯带", "LED灯带"]},
            "glass": {"type": "decimal", "required": False, "desc": "玻璃成本",
                      "aliases": ["玻璃", "玻璃成本"]},
            "electric_rail": {"type": "decimal", "required": False, "desc": "电力轨道成本",
                              "aliases": ["电力轨道", "电轨"]},
            "packing_sheet": {"type": "decimal", "required": False, "desc": "打包纸片成本",
                              "aliases": ["打包纸片", "纸片"]},
            "iron_pin": {"type": "decimal", "required": False, "desc": "铁销成本",
                         "aliases": ["铁销", "铁销成本"]},
            "connector": {"type": "decimal", "required": False, "desc": "连接片成本",
                          "aliases": ["连接片", "连接件"]},
            "aluminum_rail": {"type": "decimal", "required": False, "desc": "铝合金轨道成本",
                              "aliases": ["铝合金轨道", "铝轨"]},
            "plastic_rail": {"type": "decimal", "required": False, "desc": "塑料轨道成本",
                             "aliases": ["塑料轨道", "塑料"]},
            "mini_handle": {"type": "decimal", "required": False, "desc": "mini把手成本",
                            "aliases": ["mini把手", "小把手", "把手"]},
            "nail_free_glue": {"type": "decimal", "required": False, "desc": "免钉胶成本",
                               "aliases": ["免钉胶", "胶水"]},
            "engraving": {"type": "decimal", "required": False, "desc": "雕刻成本",
                          "aliases": ["雕刻", "雕刻费"]},
            "acrylic_strip": {"type": "decimal", "required": False, "desc": "亚克力条成本",
                              "aliases": ["亚克力条", "亚克力"]},
            "embedded_sleeve": {"type": "decimal", "required": False, "desc": "预埋套杆成本",
                                "aliases": ["预埋套杆", "套杆"]},
            "cable_mgmt": {"type": "decimal", "required": False, "desc": "理线架+插排成本",
                           "aliases": ["理线架插排", "理线架+插排", "插排"]},
            "back_panel": {"type": "decimal", "required": False, "desc": "背板成本",
                           "aliases": ["背板", "背板成本"]},
            "stainless_trim": {"type": "decimal", "required": False, "desc": "装饰条（不锈钢）成本",
                               "aliases": ["装饰条", "装饰条（不锈钢）", "装饰条(不锈钢)", "不锈钢装饰条"]},
            "leg": {"type": "decimal", "required": False, "desc": "腿部成本",
                    "aliases": ["腿部", "腿", "桌腿"]},
            "soft_pack": {"type": "decimal", "required": False, "desc": "软包成本",
                          "aliases": ["软包", "软包成本"]},
            "bed_board": {"type": "decimal", "required": False, "desc": "床铺板成本",
                          "aliases": ["床铺板", "铺板"]},
            "other_cost": {"type": "decimal", "required": False, "desc": "其他配件成本",
                           "aliases": ["其他配件", "其他", "其他成本"]},
            "other_desc": {"type": "str", "required": False, "desc": "外配件说明",
                           "aliases": ["外配件说明", "配件说明", "外配件备注"]},
            "parts_remark": {"type": "str", "required": False, "desc": "配件备注",
                             "aliases": ["配件备注", "外配备注"]},
            # ── 淘宝/平台 ID (→ pricing_sku_promo) ───────────────────
            "taobao_item_id": {"type": "str", "required": False, "desc": "淘宝商品 ID",
                               "aliases": ["淘宝商品ID", "淘宝ID", "ItemID"]},
            "taobao_url": {"type": "str", "required": False, "desc": "淘宝链接",
                           "aliases": ["淘宝链接", "淘宝商品链接", "宝贝链接"]},
            "taobao_sku_id": {"type": "str", "required": False, "desc": "淘宝 SKU ID",
                              "aliases": ["淘宝SKUID", "淘宝SKU ID"]},
            "taobao_activity_price": {"type": "decimal", "required": False, "desc": "淘宝活动报名价 (= 日常价)",
                                      "aliases": ["淘宝活动报名价", "淘宝活动价", "淘宝报名价"]},
            # ── 店内活动价 (→ pricing_sku_promo) ─────────────────────
            "shop_promo_rate": {"type": "decimal", "required": False, "desc": "店铺宝系数",
                                "aliases": ["店铺宝系数", "小促系数"]},
            "shop_internal_promo": {"type": "decimal", "required": False, "desc": "店铺宝设置价",
                                    "aliases": ["店内活动-店铺宝", "店铺宝设置", "店铺宝价"]},
            "shop_internal_final": {"type": "decimal", "required": False, "desc": "小促到手价 (公式: 日常价×店铺宝系数)",
                                    "aliases": ["店内活动-到手价", "小促到手价", "店铺宝到手价"]},
            # ── 无国补中促 (→ pricing_sku_promo) ─────────────────────
            "mid_platform_discount": {"type": "decimal", "required": False, "desc": "无国补中促 平台立减 12%",
                                      "aliases": ["无国补中促-平台立减 12%", "无国补中促-平台立减12%", "中促平台立减"]},
            "mid_shop_rate": {"type": "decimal", "required": False, "desc": "无国补中促系数 / 店铺宝",
                              "aliases": ["无国补中促-店铺宝", "无国补中促系数", "中促系数"]},
            "mid_buyer_price": {"type": "decimal", "required": False, "desc": "中促到手价 (公式)",
                                "aliases": ["无国补中促-买家到手价（不含消费券）", "无国补中促-买家到手价", "中促到手价", "无国补中促到手价"]},
            "mid_vip_commission": {"type": "decimal", "required": False, "desc": "无国补中促 88VIP佣金",
                                   "aliases": ["无国补中促-88VIP佣金", "无国补中促-88vip佣金", "中促88VIP佣金"]},
            "mid_shop_receipt": {"type": "decimal", "required": False, "desc": "中促店铺实收 (公式: 中促到手×0.99)",
                                 "aliases": ["无国补中促-店铺实收价格", "中促店铺到账", "中促到账", "中促店铺实收"]},
            "mid_vip_final": {"type": "decimal", "required": False, "desc": "中促88VIP买家最终到手价 (公式)",
                              "aliases": ["无国补中促-88vip买家最终到手价", "无国补中促-88VIP买家最终到手价", "中促会员价", "中促VIP价"]},
            # ── 无国补大促 (→ pricing_sku_promo) ─────────────────────
            "big_platform_discount": {"type": "decimal", "required": False, "desc": "无国补大促 平台立减 12%",
                                      "aliases": ["无国补大促-平台立减 12%", "无国补大促-平台立减12%", "大促平台立减"]},
            "big_shop_rate": {"type": "decimal", "required": False, "desc": "无国补大促系数 / 店铺宝设置",
                              "aliases": ["无国补大促-店铺宝设置", "无国补大促系数", "大促系数"]},
            "big_buyer_price": {"type": "decimal", "required": False, "desc": "大促到手价 (公式)",
                                "aliases": ["无国补大促-买家到手价（不含消费券）", "无国补大促-买家到手价", "大促到手价", "无国补大促到手价"]},
            "big_vip_commission": {"type": "decimal", "required": False, "desc": "无国补大促 88VIP佣金",
                                   "aliases": ["无国补大促-88VIP佣金", "无国补大促-88vip佣金", "大促88VIP佣金"]},
            "big_shop_receipt": {"type": "decimal", "required": False, "desc": "大促店铺实收 (公式: = 大促到手价)",
                                 "aliases": ["无国补大促-店铺实收价格", "大促店铺到账", "大促到账", "大促店铺实收"]},
            "big_vip_final": {"type": "decimal", "required": False, "desc": "大促买家最终到手价 (公式)",
                              "aliases": ["无国补大促-买家最终到手价", "大促会员价", "大促VIP价"]},
            # ── 小红书 (→ pricing_sku_promo) ──────────────────────────
            "xhs_item_id": {"type": "str", "required": False, "desc": "小红书商品 ID",
                            "aliases": ["小红书商品ID", "小红书ItemID"]},
            "xhs_sku_name": {"type": "str", "required": False, "desc": "小红书 SKU 名",
                             "aliases": ["小红书SKU名", "小红书规格"]},
            "xhs_sku_id": {"type": "str", "required": False, "desc": "小红书 SKU ID",
                           "aliases": ["小红书SKUID", "小红书SKU ID"]},
            "xhs_list_price": {"type": "decimal", "required": False, "desc": "小红书标价 (= 日常价)",
                               "aliases": ["RN 标价", "RN标价", "小红书标价"]},
            "xhs_activity_price": {"type": "decimal", "required": False, "desc": "小红书活动价 (RN单品宝报名价)",
                                   "aliases": ["RN单品宝报名价", "小红书活动价", "RN单品宝价", "RN活动价"]},
            "xhs_promo_discount": {"type": "decimal", "required": False, "desc": "小红书大促优惠比例 (默认0.15)",
                                   "aliases": ["RN大促优惠比例", "小红书折扣", "RN折扣", "小红书折扣率"]},
            "xhs_promo_price": {"type": "decimal", "required": False, "desc": "小红书大促价格 (公式: 活动价×(1-折扣))",
                                "aliases": ["RN大促价格", "小红书促销价", "RN促销价"]},
            # ── 备注 (→ pricing_sku) ──────────────────────────────────
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明", "注释"]},
        },
        "group_by": ["sku_code"], "parent_fields": [],
    },
    "refill_record": {
        "label": "补单记录",
        "description": "每行 = 一条补单记录 (RefillRecord). 以 order_no 去重.",
        "fields": {
            "order_no": {"type": "str", "required": True, "desc": "关联订单号",
                         "aliases": ["订单编号", "平台订单号", "订单号"]},
            "buyer_nick": {"type": "str", "required": False, "desc": "买家昵称",
                           "aliases": ["买家昵称", "买家"]},
            "refill_date": {"type": "date", "required": False, "desc": "补单日期",
                            "aliases": ["补单日期", "日期"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称",
                             "aliases": ["产品名称"]},
            "sku": {"type": "str", "required": False, "desc": "SKU",
                    "aliases": ["SKU", "规格"]},
            "qty": {"type": "int", "required": False, "desc": "数量",
                    "aliases": ["补单数量", "数量"]},
            "order_amount": {"type": "decimal", "required": False, "desc": "下单金额",
                             "aliases": ["下单金额", "补单金额"]},
            "refill_cost": {"type": "decimal", "required": False, "desc": "补单成本",
                            "aliases": ["补单成本", "成本"]},
            "refill_freight": {"type": "decimal", "required": False, "desc": "补单运费",
                               "aliases": ["补单运费", "物流费", "运费"]},
            "platform_fee": {"type": "decimal", "required": False, "desc": "平台费",
                             "aliases": ["平台费", "平台服务费"]},
            "commission": {"type": "decimal", "required": False, "desc": "佣金",
                           "aliases": ["佣金", "推广费"]},
            "total_cost": {"type": "decimal", "required": False, "desc": "总成本",
                           "aliases": ["总成本", "补单总成本"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "补单状态"]},
        },
        "group_by": ["order_no"], "parent_fields": [],
    },
    "factory_reconciliation": {
        "label": "工厂对账",
        "description": "每行 = 一条工厂对账记录 (FactoryReconciliation).",
        "fields": {
            "factory_name": {"type": "str", "required": True, "desc": "工厂名称",
                             "aliases": ["工厂名称", "工厂", "厂家"]},
            "period_start": {"type": "date", "required": False, "desc": "对账起始日期",
                             "aliases": ["对账起始", "起始日期", "月份开始"]},
            "period_end": {"type": "date", "required": False, "desc": "对账截止日期",
                           "aliases": ["对账截止", "对账日期", "截止日期"]},
            "order_amount": {"type": "decimal", "required": False, "desc": "本期下单金额",
                             "aliases": ["本期下单金额", "下单金额"]},
            "bill_amount": {"type": "decimal", "required": False, "desc": "工厂账单金额",
                            "aliases": ["工厂账单金额", "账单金额"]},
            "paid_amount": {"type": "decimal", "required": False, "desc": "已付金额",
                            "aliases": ["实际支付金额", "已付金额", "实付", "付款金额"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "status": {"type": "str", "required": False, "desc": "对账状态",
                       "aliases": ["对账状态", "状态"]},
            "diff_amount": {"type": "decimal", "required": False, "desc": "差异金额",
                            "aliases": ["差异金额", "差额"]},
            "diff_reason": {"type": "str", "required": False, "desc": "差异原因",
                            "aliases": ["差异原因", "差异说明"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "outsourcing_expense": {
        "label": "人员外包费用",
        "description": "每行 = 一条人员外包支出 (OutsourcingExpense).",
        "fields": {
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "payee": {"type": "str", "required": False, "desc": "收款人",
                      "aliases": ["收款人/平台", "收款人", "人员", "外包方"]},
            "amount": {"type": "decimal", "required": True, "desc": "金额",
                       "aliases": ["支出金额", "金额", "费用"]},
            "project": {"type": "str", "required": False, "desc": "项目",
                        "aliases": ["对应项目", "项目", "工作内容"]},
            "related_order_no": {"type": "str", "required": False, "desc": "关联订单号",
                                 "aliases": ["关联平台订单号", "订单号", "关联订单"]},
            "cost_category": {"type": "str", "required": False, "desc": "费用分类",
                              "aliases": ["费用属性", "费用分类", "类型"]},
            "payment_date": {"type": "date", "required": False, "desc": "支付日期",
                             "aliases": ["支付日期", "付款日期", "日期"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "aftersales": {
        "label": "售后表",
        "description": "每行 = 一条售后记录 (AfterSales).",
        "fields": {
            "platform_order_no": {"type": "str", "required": True, "desc": "平台订单号",
                                  "aliases": ["平台订单号", "订单编号", "订单号"]},
            "reason": {"type": "str", "required": False, "desc": "售后原因",
                       "aliases": ["售后原因", "原因", "问题类型"]},
            "compensation_fee": {"type": "decimal", "required": False, "desc": "订单赔付费",
                                 "aliases": ["订单赔付费", "赔付金额合计", "赔付金额", "赔偿金额"]},
            "good_review_refund": {"type": "decimal", "required": False, "desc": "好评/差价返",
                                   "aliases": ["好评/差价返", "好评差价返", "好评返", "差价返"]},
            "in_platform_total": {"type": "decimal", "required": False, "desc": "平台内售后总成本",
                                  "aliases": ["平台内售后总成本", "平台内售后成本"]},
            "direct_compensation": {"type": "decimal", "required": False, "desc": "直接赔付客户金额",
                                    "aliases": ["直接赔付客户金额", "直接赔付", "赔客户"]},
            "second_visit_fee": {"type": "decimal", "required": False, "desc": "二次上门维修费",
                                 "aliases": ["二次上门维修费", "二次维修费", "上门维修费"]},
            "return_pack_freight": {"type": "decimal", "required": False, "desc": "返厂打包运费",
                                    "aliases": ["返厂打包运费", "返厂运费", "退货运费"]},
            "out_platform_total": {"type": "decimal", "required": False, "desc": "平台外售后总成本",
                                   "aliases": ["平台外售后总成本", "平台外售后成本"]},
            "refill_sku": {"type": "str", "required": False, "desc": "补发SKU",
                           "aliases": ["补发SKU", "补发sku", "补发产品"]},
            "refill_tracking_no": {"type": "str", "required": False, "desc": "补发物流单号",
                                   "aliases": ["补发物流单号", "补发快递单号", "补发单号"]},
            "refill_freight": {"type": "decimal", "required": False, "desc": "补发运费",
                               "aliases": ["补发运费", "补发物流费"]},
            "wanshifu_deduction": {"type": "decimal", "required": False, "desc": "万师傅扣款",
                                   "aliases": ["万师傅扣款", "万师傅扣费"]},
            "factory_compensation": {"type": "decimal", "required": False, "desc": "工厂补偿金额",
                                     "aliases": ["工厂补偿金额", "工厂补偿"]},
            "logistics_compensation": {"type": "decimal", "required": False, "desc": "物流补偿金额",
                                       "aliases": ["物流补偿金额", "物流补偿"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "second_inbound_confirmed": {"type": "str", "required": False, "desc": "二次入库确认",
                                         "aliases": ["二次入库确认", "二次入库"]},
            "processed_at": {"type": "date", "required": False, "desc": "处理日期",
                             "aliases": ["售后处理日期", "处理日期", "日期"]},
            "status": {"type": "str", "required": False, "desc": "售后状态",
                       "aliases": ["售后状态", "状态"]},
            "customer_satisfaction": {"type": "str", "required": False, "desc": "客户满意度",
                                      "aliases": ["客户满意度", "满意度"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "competitor_price": {
        "label": "竞品价目",
        "description": "每行 = 一条竞品 SKU 价 (CompetitorPrice), 供微定制旁参考。",
        "fields": {
            "store": {"type": "str", "required": False, "desc": "店铺名",
                      "aliases": ["店铺名", "店铺", "店名"]},
            "category": {"type": "str", "required": False, "desc": "类目",
                         "aliases": ["类目", "品类", "分类"]},
            "product": {"type": "str", "required": False, "desc": "产品",
                        "aliases": ["产品", "产品名", "品名"]},
            "link": {"type": "str", "required": False, "desc": "链接",
                     "aliases": ["链接", "网址", "URL", "link"]},
            "wood": {"type": "str", "required": False, "desc": "木材",
                     "aliases": ["木材", "材质", "主材"]},
            "sku_name": {"type": "str", "required": True, "desc": "SKU 名",
                         "aliases": ["SKU 名", "SKU名", "SKU", "规格", "款式"]},
            "daily_price": {"type": "decimal", "required": False, "desc": "日常活动价",
                            "aliases": ["日常活动价", "日常价", "活动价", "价格", "售价"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "delivery_note": {
        "label": "供应商送货单",
        "description": "每行是一行明细; 同一 supplier_name + note_no 的行合并为一张送货单。",
        "fields": {
            "supplier_name": {
                "type": "str", "required": True,
                "desc": "供应商名称 (没注册过会自动创建)",
                "aliases": ["供应商", "厂家", "工厂", "供货商", "Supplier"],
            },
            "note_no": {
                "type": "str", "required": False,
                "desc": "送货单号",
                "aliases": ["单号", "送货单号", "单据号", "票号", "NoteNo", "DN号"],
            },
            "delivery_date": {
                "type": "date", "required": True,
                "desc": "送货/到货日期",
                "aliases": ["日期", "送货日期", "到货日期", "下单日期", "出库日期", "Date"],
            },
            "item_name": {
                "type": "str", "required": True,
                "desc": "品名/商品名",
                "aliases": ["品名", "商品", "商品名", "货品", "名称", "Item"],
            },
            "spec": {
                "type": "str", "required": False,
                "desc": "规格尺寸 (如 1800×850)",
                "aliases": ["规格", "尺寸", "型号", "Spec", "Size"],
            },
            "unit": {
                "type": "str", "required": False,
                "desc": "单位 (件/张/块/片/套)",
                "aliases": ["单位", "Unit"],
            },
            "qty": {
                "type": "decimal", "required": True,
                "desc": "数量",
                "aliases": ["数量", "件数", "Qty", "Quantity"],
            },
            "unit_price": {
                "type": "decimal", "required": False,
                "desc": "单价 (元)",
                "aliases": ["单价", "单价(元)", "Price", "UnitPrice"],
            },
            "amount": {
                "type": "decimal", "required": False,
                "desc": "金额 (元, 缺省会用 单价×数量 自动填)",
                "aliases": ["金额", "合计", "小计", "总额", "Amount", "Total"],
            },
            "total_amount": {
                "type": "decimal", "required": False,
                "desc": "整张单总金额 (如果 Excel 单独列了一张单的合计, 写这里)",
                "aliases": ["单据合计", "票面金额", "总计"],
            },
            "status": {
                "type": "str", "required": False,
                "desc": "状态: pending_review/confirmed/billed/paid/disputed",
                "aliases": ["状态", "对账状态", "付款状态"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "说明", "Note", "Remark"],
            },
        },
        "group_by": ["supplier_name", "note_no"],
        "parent_fields": ["supplier_name", "note_no", "delivery_date",
                          "total_amount", "status", "remark"],
    },
    "alipay_flow": {
        "label": "支付宝流水",
        "description": "导入支付宝导出的 Excel/CSV (任意列结构)。一行 = 一条 AlipayFlow。",
        "fields": {
            "account": {
                "type": "str", "required": False,  # 通常从 sheet 名推导, 不强制要求列
                "desc": "支付宝账户 (企业号 / 个体户私账 / 爱群号 / 佳宝号 / 主力号)",
                "aliases": ["账户", "账号", "支付宝账号", "Account"],
            },
            "transaction_no": {
                "type": "str", "required": True,
                "desc": "交易流水号 (同一账户内全局唯一)",
                "aliases": ["交易流水号", "流水号", "交易号", "TransactionNo", "单号"],
            },
            "transaction_time": {
                "type": "datetime", "required": False,
                "desc": "交易时间",
                "aliases": ["交易时间", "时间", "Time"],
            },
            "transaction_type": {
                "type": "str", "required": False,
                "desc": "交易类型 (在线支付 / 转账 / 分账 / ...)",
                "aliases": ["交易类型", "类型", "Type"],
            },
            "counterparty": {
                "type": "str", "required": False,
                "desc": "对手方姓名/公司",
                "aliases": ["交易对象", "交易对方", "对方", "对手方", "对方姓名", "收款方"],
            },
            "counterparty_account": {
                "type": "str", "required": False,
                "desc": "对手方账号",
                "aliases": ["交易账户", "对方账号", "收款账号"],
            },
            "amount": {
                "type": "decimal", "required": True,
                "desc": "金额 (正=收入, 负=支出; 如果 Excel 是 收入/支出 分开两列, 请只选其一并加负号)",
                "aliases": ["收支金额", "金额", "收支", "Amount"],
            },
            "balance": {
                "type": "decimal", "required": False,
                "desc": "交易后余额",
                "aliases": ["余额", "账户余额", "Balance"],
            },
            "related_order_no": {
                "type": "str", "required": False,
                "desc": "关联的平台订单号",
                "aliases": ["关联订单号", "商户订单号", "订单号", "OrderNo"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "摘要", "Note"],
            },
        },
        "group_by": ["account", "transaction_no"],
        "parent_fields": list(),
    },
    "factory_order": {
        "label": "工厂下单",
        "description": "每行 = 一张工厂订单 (FactoryOrder)。",
        "fields": {
            "factory_order_no": {
                "type": "str", "required": False,
                "desc": "工厂订单号 (留空系统自动生成 畔色0001 序列)",
                "aliases": ["工厂订单号", "下单号", "厂单号"],
            },
            "platform_order_no": {
                "type": "str", "required": False,
                "desc": "对应的平台订单号 (淘宝/抖音)",
                "aliases": ["关联平台订单号", "平台订单号", "淘宝单号", "订单号"],
            },
            "factory_name": {
                "type": "str", "required": False,
                "desc": "工厂名",
                "aliases": ["工厂名称", "工厂", "厂家", "供应商"],
            },
            "order_date": {
                "type": "date", "required": False,
                "desc": "下单日期",
                "aliases": ["下单日期", "日期"],
            },
            "expected_delivery": {
                "type": "date", "required": False,
                "desc": "预计交付日期",
                "aliases": ["要求交货日期", "预计交付", "交期", "预计到货"],
            },
            "actual_delivery": {
                "type": "date", "required": False,
                "desc": "实际交付日期",
                "aliases": ["实际交货日期", "实际交付", "实际到货", "到货日期"],
            },
            "product_code": {
                "type": "str", "required": False,
                "desc": "产品编码",
                "aliases": ["产品编码", "货号", "型号"],
            },
            "sku": {
                "type": "str", "required": False,
                "desc": "SKU/规格描述",
                "aliases": ["SKU", "规格", "款式"],
            },
            "qty": {
                "type": "int", "required": False,
                "desc": "数量",
                "aliases": ["数量", "件数"],
            },
            "unit_price": {
                "type": "decimal", "required": False,
                "desc": "单价",
                "aliases": ["工厂单价", "单价", "Price"],
            },
            "factory_bill_amount": {
                "type": "decimal", "required": False,
                "desc": "工厂账单金额",
                "aliases": ["工厂账单金额", "工厂账单", "账单金额", "金额"],
            },
            "expected_amount": {
                "type": "decimal", "required": False,
                "desc": "产品预期金额 (留空系统按定价表总出厂成本自动算)",
                "aliases": ["产品预期金额", "预期金额", "预期成本"],
            },
            "payment_method": {
                "type": "str", "required": False,
                "desc": "付款方式 (月结/现付/预付)",
                "aliases": ["付款方式", "结算"],
            },
            "payment_status": {
                "type": "str", "required": False,
                "desc": "付款状态",
                "aliases": ["付款状态", "对账"],
            },
            "payment_date": {
                "type": "date", "required": False,
                "desc": "付款日期 (匹配支付宝流水后自动填)",
                "aliases": ["付款日期"],
            },
            "carrier": {
                "type": "str", "required": False,
                "desc": "物流方式",
                "aliases": ["物流方式", "物流公司", "承运商"],
            },
            "tracking_no": {
                "type": "str", "required": False,
                "desc": "物流单号",
                "aliases": ["物流单号", "快递单号", "运单号"],
            },
            "alipay_flow_no": {
                "type": "str", "required": False,
                "desc": "支付宝流水号 (工厂月结付款后填, 触发付款状态翻已付款)",
                "aliases": ["支付宝流水号", "流水号"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "说明"],
            },
            "internal_order_no": {
                "type": "str", "required": False,
                "desc": "内部单号 (Panse+年+序号, 系统自动生成, 无需填写)",
                "aliases": ["内部单号", "Panse单号", "内部编号"],
            },
        },
        "group_by": ["factory_order_no"],
        "parent_fields": list(),  # factory_order 整体是一行, 无父子
    },
    "daily_operations": {
        "label": "日常经营",
        "description": "每行 = 一笔日常经营收支记录 (DailyOperation).",
        "fields": {
            "record_date": {"type": "date", "required": False, "desc": "日期",
                            "aliases": ["日期", "记录日期", "Date"]},
            "category": {"type": "str", "required": False, "desc": "大类",
                         "aliases": ["大类", "类别", "分类", "Category"]},
            "item": {"type": "str", "required": False, "desc": "项目/摘要",
                     "aliases": ["项目", "摘要", "事项", "Item"]},
            "amount": {"type": "decimal", "required": False, "desc": "金额",
                       "aliases": ["金额", "Amount"]},
            "qty": {"type": "decimal", "required": False, "desc": "数量",
                    "aliases": ["数量", "Qty"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位", "Unit"]},
            "payment_account": {"type": "str", "required": False, "desc": "支付账户",
                                "aliases": ["支付账户", "账户", "付款账户"]},
            "expense_type": {"type": "str", "required": False, "desc": "支出类型",
                             "aliases": ["支出类型", "收支类型", "类型"]},
            "recipient": {"type": "str", "required": False, "desc": "支付对象",
                          "aliases": ["支付对象", "收款方", "对方"]},
            "payment_method": {"type": "str", "required": False, "desc": "支付方式",
                               "aliases": ["支付方式", "付款方式"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "invoice_status": {"type": "str", "required": False, "desc": "发票状态",
                               "aliases": ["发票状态", "发票"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
    },
    "order_details": {
        "label": "订单细节",
        "description": "每行 = 一条 SKU 级订单与物料对应关系 (OrderDetail).",
        "fields": {
            "order_no": {"type": "str", "required": False, "desc": "订单编号",
                         "aliases": ["订单编号", "订单号"]},
            "factory_order_no": {"type": "str", "required": False, "desc": "工厂订单号",
                                 "aliases": ["工厂订单号", "工厂订单"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码", "货号"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称",
                             "aliases": ["产品名称", "产品"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU编码",
                         "aliases": ["SKU编码", "SKU code"]},
            "sku_name": {"type": "str", "required": False, "desc": "SKU名称",
                         "aliases": ["SKU名称", "SKU"]},
            "bom_material_code": {"type": "str", "required": False, "desc": "关联BOM物料编码",
                                  "aliases": ["关联BOM物料编码", "BOM物料编码", "物料编码"]},
            "material_name": {"type": "str", "required": False, "desc": "关联物料名称",
                              "aliases": ["关联物料名称", "物料名称"]},
        },
    },
    "wood_loss": {
        "label": "木材损耗",
        "description": "每行 = 一批次木材的入库/使用/损耗记录.",
        "fields": {
            "purchase_date": {"type": "date", "required": False, "desc": "购买日期",
                              "aliases": ["购买日期", "采购日期"]},
            "wood_type": {"type": "str", "required": False, "desc": "木材种类",
                          "aliases": ["木材种类", "材种", "树种", "木材"]},
            "spec": {"type": "str", "required": False, "desc": "规格",
                     "aliases": ["规格(长×宽×厚)", "规格", "尺寸"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位"]},
            "inbound_qty": {"type": "decimal", "required": False, "desc": "入库数量",
                            "aliases": ["入库数量", "入库量", "数量"]},
            "used_qty": {"type": "decimal", "required": False, "desc": "实际使用量",
                         "aliases": ["实际使用量", "使用量", "实用量"]},
            "loss_qty": {"type": "decimal", "required": False, "desc": "损耗数量",
                         "aliases": ["损耗数量", "损耗量", "损耗"]},
            "loss_rate_pct": {"type": "decimal", "required": False, "desc": "损耗率%",
                              "aliases": ["损耗率%", "损耗率", "损耗比例"]},
            "related_product_qty": {"type": "decimal", "required": False, "desc": "对应使用产品量",
                                    "aliases": ["对应使用产品量", "产品量", "可做家具数"]},
            "reason": {"type": "str", "required": False, "desc": "损耗原因",
                       "aliases": ["损耗原因", "原因"]},
            "disposition": {"type": "str", "required": False, "desc": "处理方式",
                            "aliases": ["处理方式", "处理"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
    },
    "sample": {
        "label": "样品表",
        "description": "每行 = 一件样品的位置/状态/去向记录.",
        "fields": {
            "sample_no": {"type": "str", "required": True, "desc": "样品编号",
                          "aliases": ["样品编号", "编号", "样品号"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码", "货号"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称",
                             "aliases": ["产品名称", "产品"]},
            "sku": {"type": "str", "required": False, "desc": "SKU",
                    "aliases": ["SKU", "规格"]},
            "sample_type": {"type": "str", "required": False, "desc": "样品类型",
                            "aliases": ["样品类型", "类型"]},
            "qty": {"type": "int", "required": False, "desc": "数量",
                    "aliases": ["数量"]},
            "made_at": {"type": "date", "required": False, "desc": "制作日期",
                        "aliases": ["制作日期", "制作时间"]},
            "cost": {"type": "decimal", "required": False, "desc": "制作成本",
                     "aliases": ["制作成本", "成本"]},
            "location": {"type": "str", "required": False, "desc": "存放地点",
                         "aliases": ["存放地点", "位置", "地点"]},
            "status": {"type": "str", "required": False, "desc": "使用状态",
                       "aliases": ["使用状态", "状态"]},
            "usage": {"type": "str", "required": False, "desc": "用途",
                      "aliases": ["用途", "使用用途"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
    },
    "promotion_flow": {
        "label": "推广记录",
        "description": "每行 = 一笔推广账户的充值/消耗流水 (PromotionFlow).",
        "fields": {
            "transaction_date": {"type": "date", "required": False, "desc": "交易日期",
                                 "aliases": ["交易日期", "日期", "交易时间"]},
            "flow_type": {"type": "str", "required": False, "desc": "收支类型",
                          "aliases": ["收支类型", "类型", "流水类型"]},
            "amount": {"type": "decimal", "required": False, "desc": "流水金额",
                       "aliases": ["流水金额", "金额", "充值金额", "消耗金额"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
    },
    "part_purchase": {
        "label": "配件采购记录",
        "description": "每行 = 一条配件采购记录 (PartPurchase). 以 采购单号 去重, 留空自动生成.",
        "fields": {
            "purchase_no": {"type": "str", "required": False, "desc": "采购单号 (留空自动生成 CG 序列)",
                            "aliases": ["采购单号", "采购编号"]},
            "supplier": {"type": "str", "required": False, "desc": "供应商名称",
                         "aliases": ["供应商名称", "供应商", "厂家", "供货商"]},
            "purchase_date": {"type": "date", "required": False, "desc": "采购日期",
                              "aliases": ["采购日期", "日期"]},
            "material_code": {"type": "str", "required": False, "desc": "配件编码",
                              "aliases": ["配件编码", "物料编码"]},
            "material_name": {"type": "str", "required": False, "desc": "配件名称",
                              "aliases": ["配件名称", "物料名称", "品名"]},
            "spec": {"type": "str", "required": False, "desc": "规格型号",
                     "aliases": ["规格型号", "规格", "型号"]},
            "qty": {"type": "decimal", "required": False, "desc": "数量",
                    "aliases": ["数量", "采购数量"]},
            "unit_price": {"type": "decimal", "required": False, "desc": "采购单价",
                           "aliases": ["采购单价", "单价"]},
            "amount": {"type": "decimal", "required": False, "desc": "金额",
                       "aliases": ["金额", "采购金额", "小计"]},
            "tracking_no": {"type": "str", "required": False, "desc": "物流单号",
                            "aliases": ["物流单号", "快递单号"]},
            "freight": {"type": "decimal", "required": False, "desc": "运费",
                        "aliases": ["运费", "物流费"]},
            "total_amount": {"type": "decimal", "required": False, "desc": "总金额",
                             "aliases": ["总金额", "合计", "总计"]},
            "purchase_type": {"type": "str", "required": False, "desc": "采购类型",
                              "aliases": ["采购类型", "类型"]},
            "related_order_no": {"type": "str", "required": False, "desc": "关联订单号",
                                 "aliases": ["关联订单号", "关联平台订单号", "订单号"]},
            "payment_method": {"type": "str", "required": False, "desc": "付款方式",
                               "aliases": ["付款方式", "结算方式"]},
            "payment_status": {"type": "str", "required": False, "desc": "付款状态",
                               "aliases": ["付款状态"]},
            "payment_date": {"type": "date", "required": False, "desc": "付款日期",
                             "aliases": ["付款日期"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "brand_marketing": {
        "label": "品牌营销",
        "description": "每行 = 一个品牌营销项目 (BrandMarketing).",
        "fields": {
            "project_name": {"type": "str", "required": True, "desc": "项目名称",
                             "aliases": ["项目名称", "项目"]},
            "project_type": {"type": "str", "required": False, "desc": "项目类型",
                             "aliases": ["项目类型", "类型"]},
            "partner": {"type": "str", "required": False, "desc": "合作方",
                        "aliases": ["合作方", "合作伙伴"]},
            "start_date": {"type": "date", "required": False, "desc": "开始日期",
                           "aliases": ["开始日期", "起始日期"]},
            "end_date": {"type": "date", "required": False, "desc": "结束日期",
                         "aliases": ["结束日期", "截止日期"]},
            "budget": {"type": "decimal", "required": False, "desc": "预算金额",
                       "aliases": ["预算金额", "预算"]},
            "actual_spend": {"type": "decimal", "required": False, "desc": "实际支出",
                             "aliases": ["实际支出", "实际花费"]},
            "payment_date": {"type": "date", "required": False, "desc": "付款日期",
                             "aliases": ["付款日期"]},
            "status": {"type": "str", "required": False, "desc": "项目状态",
                       "aliases": ["项目状态", "状态"]},
            "effect_eval": {"type": "str", "required": False, "desc": "效果评估",
                            "aliases": ["效果评估", "效果", "评估"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "说明"]},
        },
        "group_by": [], "parent_fields": [],
    },
}


def get_schema(entity_type: str) -> EntitySchema:
    if entity_type not in ENTITY_SCHEMAS:
        raise ValueError(f"未知实体类型: {entity_type}. 支持: {list(ENTITY_SCHEMAS)}")
    return ENTITY_SCHEMAS[entity_type]


def list_entity_types() -> list[dict]:
    return [
        {"value": k, "label": v["label"], "description": v["description"]}
        for k, v in ENTITY_SCHEMAS.items()
    ]
