"""Excel importer 的目标 schema 定义.

每个 entity 描述: 目标字段集 + 字段类型 + 是否必填 + 别名提示 (给 AI 推断用)。
新增 entity 只需在这里加一项, importer / API / 前端会自动支持。
"""
from __future__ import annotations

from typing import Literal, TypedDict


FieldType = Literal["str", "int", "decimal", "date", "datetime", "bool"]


class FieldDef(TypedDict, total=False):
    type: FieldType
    required: bool
    desc: str
    aliases: list[str]  # 给 AI 提示: "这个字段在 Excel 里常见的列名"


class EntitySchema(TypedDict):
    label: str
    description: str
    fields: dict[str, FieldDef]
    group_by: list[str]   # 同一组的行合并为一个父对象 (如 同 note_no → 一张 DeliveryNote)
    parent_fields: list[str]  # 这些字段属于父对象, 其他属于明细行


ENTITY_SCHEMAS: dict[str, EntitySchema] = {
    "product": {
        "label": "产品总表",
        "description": "每行 = 一个产品 (Product). 同 code 已存在会更新.",
        "fields": {
            "code": {"type": "str", "required": True, "desc": "产品编码",
                     "aliases": ["产品编码", "产品 code", "ProductCode", "SPU 编码"]},
            "name": {"type": "str", "required": True, "desc": "产品名称",
                     "aliases": ["产品名称", "产品名", "Name", "商品名"]},
            "category": {"type": "str", "required": False, "desc": "类目",
                         "aliases": ["类目", "分类", "Category"]},
            "brand": {"type": "str", "required": False, "desc": "品牌",
                      "aliases": ["品牌", "Brand"]},
            "image_url": {"type": "str", "required": False, "desc": "图片链接",
                          "aliases": ["图片链接", "图片", "图片URL", "主图链接"]},
            "custom_scope": {"type": "str", "required": False, "desc": "定制范围",
                             "aliases": ["定制范围"]},
            "size_detail": {"type": "str", "required": False, "desc": "尺寸明细",
                            "aliases": ["尺寸明细", "尺寸"]},
            "aux_material": {"type": "str", "required": False, "desc": "辅材介绍",
                             "aliases": ["辅材介绍", "辅材"]},
            "description": {"type": "str", "required": False, "desc": "产品文案",
                            "aliases": ["产品文案介绍", "产品文案", "文案介绍", "文案"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "Remark"]},
            "taobao_id": {"type": "str", "required": False, "desc": "淘宝商品 ID",
                          "aliases": ["淘宝 ID", "淘宝商品 ID", "TaobaoID"]},
        },
        "group_by": ["code"], "parent_fields": [],
    },
    "material": {
        "label": "物料 / 配件价格",
        "description": "每行 = 一个物料 (Material).",
        "fields": {
            "code": {"type": "str", "required": True, "desc": "物料编码",
                     "aliases": ["物料编码", "配件编码", "Code"]},
            "name": {"type": "str", "required": True, "desc": "物料名称",
                     "aliases": ["物料名称", "配件名称", "名称", "Name"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位", "Unit"]},
            "size_type": {"type": "str", "required": False, "desc": "尺寸类型 (组合/个数)",
                          "aliases": ["尺寸类型"]},
            "price": {"type": "decimal", "required": False, "desc": "单价",
                      "aliases": ["计算价格", "单价", "Price"]},
            "lead_time_days": {"type": "int", "required": False, "desc": "补货周期天数",
                               "aliases": ["补货周期", "lead time", "LeadTime"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "Remark"]},
        },
        "group_by": ["code"], "parent_fields": [],
    },
    "bom_line": {
        "label": "BOM 物料分解",
        "description": "每行 = 一条 BOM (产品+SKU+物料+用量).",
        "fields": {
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码", "产品 code"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU 编码",
                         "aliases": ["SKU编码", "SKU code"]},
            "material_code": {"type": "str", "required": True, "desc": "物料编码",
                              "aliases": ["物料编码", "配件编码"]},
            "qty_per_product": {"type": "decimal", "required": True, "desc": "单产品用量",
                                "aliases": ["单产品用量", "用量", "数量", "Qty"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位", "Unit"]},
            "size_type": {"type": "str", "required": False, "desc": "尺寸类型",
                          "aliases": ["尺寸类型"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "product_inventory": {
        "label": "成品库存",
        "description": "每行 = 一条成品库存 (按 仓库+产品+SKU 唯一).",
        "fields": {
            "warehouse": {"type": "str", "required": False, "desc": "仓库 (默认 江西仓库)",
                          "aliases": ["仓库", "仓库名称"]},
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "sku": {"type": "str", "required": False, "desc": "SKU",
                    "aliases": ["SKU", "规格"]},
            "spec": {"type": "str", "required": False, "desc": "规格尺寸",
                     "aliases": ["规格尺寸", "规格"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位"]},
            "physical_qty": {"type": "decimal", "required": False, "desc": "物理库存",
                             "aliases": ["物理库存", "实物库存", "库存"]},
            "locked_qty": {"type": "decimal", "required": False, "desc": "锁定库存",
                           "aliases": ["锁定库存", "已锁"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "part_inventory": {
        "label": "配件库存",
        "description": "每行 = 一条配件库存 (按 仓库+物料 唯一).",
        "fields": {
            "warehouse": {"type": "str", "required": False, "desc": "仓库",
                          "aliases": ["仓库", "仓库名称"]},
            "material_code": {"type": "str", "required": True, "desc": "物料编码",
                              "aliases": ["物料编码", "配件编码"]},
            "spec": {"type": "str", "required": False, "desc": "规格型号",
                     "aliases": ["规格型号", "规格"]},
            "unit": {"type": "str", "required": False, "desc": "单位",
                     "aliases": ["单位"]},
            "physical_qty": {"type": "decimal", "required": False, "desc": "物理库存",
                             "aliases": ["物理库存", "库存"]},
            "locked_qty": {"type": "decimal", "required": False, "desc": "锁定库存",
                           "aliases": ["锁定库存"]},
            "safety_stock": {"type": "decimal", "required": False, "desc": "安全库存",
                             "aliases": ["安全库存"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "order": {
        "label": "订单总表",
        "description": "每行 = 一张平台订单 (Order).",
        "fields": {
            "platform": {"type": "str", "required": False, "desc": "平台 (淘宝/抖音/京东等)",
                         "aliases": ["平台", "Platform"]},
            "order_no": {"type": "str", "required": True, "desc": "订单号 (唯一)",
                         "aliases": ["订单编号", "订单号", "OrderNo"]},
            "order_date": {"type": "date", "required": False, "desc": "下单日期",
                           "aliases": ["下单日期", "订单日期"]},
            "ship_date": {"type": "date", "required": False, "desc": "发货日期",
                          "aliases": ["发货日期"]},
            "customer_name": {"type": "str", "required": False, "desc": "客户姓名",
                              "aliases": ["客户姓名", "买家"]},
            "customer_phone": {"type": "str", "required": False, "desc": "电话",
                               "aliases": ["联系电话", "电话", "手机"]},
            "customer_address": {"type": "str", "required": False, "desc": "地址",
                                 "aliases": ["收货地址", "地址"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码", "货号"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名",
                             "aliases": ["产品名称", "商品名"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": False, "desc": "SKU 编码",
                         "aliases": ["SKU编码", "SKU code"]},
            "qty": {"type": "int", "required": False, "desc": "数量",
                    "aliases": ["数量", "件数"]},
            "paid_amount": {"type": "decimal", "required": False, "desc": "实付金额",
                            "aliases": ["实付金额", "实付", "付款金额", "买家实付金额"]},
            "discount": {"type": "decimal", "required": False, "desc": "优惠金额",
                         "aliases": ["优惠金额", "折扣金额", "优惠"]},
            "platform_fee": {"type": "decimal", "required": False, "desc": "平台服务费",
                             "aliases": ["平台服务费", "佣金"]},
            "carrier": {"type": "str", "required": False, "desc": "快递公司",
                        "aliases": ["快递公司", "物流公司", "承运商"]},
            "tracking_no": {"type": "str", "required": False, "desc": "快递单号",
                            "aliases": ["快递单号", "物流单号", "快递号"]},
            "theoretical_cost": {"type": "decimal", "required": False, "desc": "产品理论成本",
                                 "aliases": ["产品理论成本", "理论成本"]},
            "actual_cost": {"type": "decimal", "required": False, "desc": "产品实际成本",
                            "aliases": ["产品实际成本", "实际成本"]},
            "actual_freight": {"type": "decimal", "required": False, "desc": "实际运费",
                               "aliases": ["实际运费", "运费"]},
            "is_custom": {"type": "bool", "required": False, "desc": "是否定制",
                          "aliases": ["是否定制", "是否微定制", "定制"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": ["order_no"], "parent_fields": [],
    },
    "account_balance": {
        "label": "账户月度余额",
        "description": "每行 = 一个账户某月的开/收/支/期末.",
        "fields": {
            "account_name": {"type": "str", "required": True, "desc": "账户名",
                             "aliases": ["账户名称", "账户", "账户名"]},
            "year": {"type": "int", "required": True, "desc": "年",
                     "aliases": ["年", "年份", "Year"]},
            "month": {"type": "int", "required": True, "desc": "月",
                      "aliases": ["月", "月份", "Month"]},
            "opening_balance": {"type": "decimal", "required": False, "desc": "期初余额",
                                "aliases": ["期初余额", "期初"]},
            "income": {"type": "decimal", "required": False, "desc": "收入",
                       "aliases": ["收入", "收"]},
            "expense": {"type": "decimal", "required": False, "desc": "支出",
                        "aliases": ["支出", "支"]},
            "closing_balance": {"type": "decimal", "required": False, "desc": "期末余额",
                                "aliases": ["期末余额", "期末"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "pricing_sku": {
        "label": "定价总表 (SKU 四档售价)",
        "description": "每行 = 一个 SKU 的定价快照 (标价/日常/小促/中促/大促 + 成本拆分).",
        "fields": {
            "product_code": {"type": "str", "required": True, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "sku": {"type": "str", "required": False, "desc": "SKU 描述",
                    "aliases": ["SKU", "规格"]},
            "sku_code": {"type": "str", "required": True, "desc": "SKU 编码 (唯一)",
                         "aliases": ["SKU编码", "SKU code"]},
            "size_category": {"type": "str", "required": False, "desc": "大小分类 (小型/中型/大型)",
                              "aliases": ["大小分类", "尺寸分类", "产品大小类型", "大小类型", "Size"]},
            "image_url": {"type": "str", "required": False, "desc": "图片链接",
                          "aliases": ["图片链接", "图片", "图片URL", "主图链接"]},
            "list_price": {"type": "decimal", "required": False, "desc": "标价",
                           "aliases": ["标价", "标价计算", "List"]},
            "daily_price": {"type": "decimal", "required": False, "desc": "日常价 / 单品宝",
                            "aliases": ["日常价/单品宝", "日常价", "日常", "单品宝"]},
            "small_promo": {"type": "decimal", "required": False, "desc": "小促价 (超级立减)",
                            "aliases": ["小促价（超级立减）", "小促价", "小促", "超级立减", "立减价"]},
            "mid_promo": {"type": "decimal", "required": False, "desc": "中促价 (88 券)",
                          "aliases": ["中促价（88券活动）", "中促价", "中促", "88券", "88 券"]},
            "big_promo": {"type": "decimal", "required": False, "desc": "大促价 (双11)",
                          "aliases": ["大促到手价（双11）", "大促价", "大促", "双11", "双 11"]},
            "gross_margin_rate": {"type": "decimal", "required": False, "desc": "毛利率",
                                  "aliases": ["毛利率", "即时毛利率"]},
            "big_promo_margin": {"type": "decimal", "required": False, "desc": "大促利润",
                                 "aliases": ["大促利润", "利润"]},
            "accounting_cost": {"type": "decimal", "required": False, "desc": "会计总成本",
                                "aliases": ["会计总成本", "总成本", "成本"]},
            "physical_cost": {"type": "decimal", "required": False, "desc": "物理成本",
                              "aliases": ["物理总成本", "物理成本"]},
            "platform_fee_rate": {"type": "decimal", "required": False, "desc": "平台费率",
                                  "aliases": ["平台费率", "佣金率"]},
            "tax": {"type": "decimal", "required": False, "desc": "税费金额",
                    "aliases": ["税", "税费"]},
        },
        "group_by": ["sku_code"], "parent_fields": [],
    },
    "refill_record": {
        "label": "补单记录",
        "description": "每行 = 一条补单记录 (RefillRecord). 以 order_no 去重.",
        "fields": {
            "order_no": {"type": "str", "required": True, "desc": "关联订单号",
                         "aliases": ["订单编号", "平台订单号", "订单号"]},
            "buyer_nick": {"type": "str", "required": False, "desc": "买家昵称",
                           "aliases": ["买家昵称", "买家"]},
            "refill_date": {"type": "date", "required": False, "desc": "补单日期",
                            "aliases": ["补单日期", "日期"]},
            "product_code": {"type": "str", "required": False, "desc": "产品编码",
                             "aliases": ["产品编码"]},
            "product_name": {"type": "str", "required": False, "desc": "产品名称",
                             "aliases": ["产品名称"]},
            "sku": {"type": "str", "required": False, "desc": "SKU",
                    "aliases": ["SKU", "规格"]},
            "qty": {"type": "int", "required": False, "desc": "数量",
                    "aliases": ["补单数量", "数量"]},
            "order_amount": {"type": "decimal", "required": False, "desc": "下单金额",
                             "aliases": ["下单金额", "补单金额"]},
            "refill_cost": {"type": "decimal", "required": False, "desc": "补单成本",
                            "aliases": ["补单成本", "成本"]},
            "refill_freight": {"type": "decimal", "required": False, "desc": "补单运费",
                               "aliases": ["补单运费", "物流费", "运费"]},
            "platform_fee": {"type": "decimal", "required": False, "desc": "平台费",
                             "aliases": ["平台费", "平台服务费"]},
            "commission": {"type": "decimal", "required": False, "desc": "佣金",
                           "aliases": ["佣金", "推广费"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注", "补单状态"]},
        },
        "group_by": ["order_no"], "parent_fields": [],
    },
    "factory_reconciliation": {
        "label": "工厂对账",
        "description": "每行 = 一条工厂对账记录 (FactoryReconciliation).",
        "fields": {
            "factory_name": {"type": "str", "required": True, "desc": "工厂名称",
                             "aliases": ["工厂名称", "工厂", "厂家"]},
            "period_start": {"type": "date", "required": False, "desc": "对账起始日期",
                             "aliases": ["对账起始", "起始日期", "月份开始"]},
            "period_end": {"type": "date", "required": False, "desc": "对账截止日期",
                           "aliases": ["对账截止", "对账日期", "截止日期"]},
            "order_amount": {"type": "decimal", "required": False, "desc": "本期下单金额",
                             "aliases": ["本期下单金额", "下单金额"]},
            "bill_amount": {"type": "decimal", "required": False, "desc": "工厂账单金额",
                            "aliases": ["工厂账单金额", "账单金额"]},
            "paid_amount": {"type": "decimal", "required": False, "desc": "已付金额",
                            "aliases": ["已付金额", "实付", "付款金额"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "status": {"type": "str", "required": False, "desc": "对账状态",
                       "aliases": ["对账状态", "状态"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "outsourcing_expense": {
        "label": "人员外包费用",
        "description": "每行 = 一条人员外包支出 (OutsourcingExpense).",
        "fields": {
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "payee": {"type": "str", "required": False, "desc": "收款人",
                      "aliases": ["收款人", "人员", "外包方"]},
            "amount": {"type": "decimal", "required": True, "desc": "金额",
                       "aliases": ["支出金额", "金额", "费用"]},
            "project": {"type": "str", "required": False, "desc": "项目",
                        "aliases": ["项目", "工作内容"]},
            "related_order_no": {"type": "str", "required": False, "desc": "关联订单号",
                                 "aliases": ["关联平台订单号", "订单号", "关联订单"]},
            "cost_category": {"type": "str", "required": False, "desc": "费用分类",
                              "aliases": ["费用分类", "类型"]},
            "payment_date": {"type": "date", "required": False, "desc": "支付日期",
                             "aliases": ["支付日期", "付款日期", "日期"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "aftersales": {
        "label": "售后表",
        "description": "每行 = 一条售后记录 (AfterSales).",
        "fields": {
            "platform_order_no": {"type": "str", "required": True, "desc": "平台订单号",
                                  "aliases": ["平台订单号", "订单编号", "订单号"]},
            "reason": {"type": "str", "required": False, "desc": "售后原因",
                       "aliases": ["售后原因", "原因", "问题类型"]},
            "compensation_fee": {"type": "decimal", "required": False, "desc": "赔付金额合计",
                                 "aliases": ["赔付金额合计", "赔付金额", "赔偿金额"]},
            "direct_compensation": {"type": "decimal", "required": False, "desc": "直接赔付客户金额",
                                    "aliases": ["直接赔付客户金额", "直接赔付", "赔客户"]},
            "factory_compensation": {"type": "decimal", "required": False, "desc": "工厂补偿金额",
                                     "aliases": ["工厂补偿金额", "工厂补偿"]},
            "alipay_flow_no": {"type": "str", "required": False, "desc": "支付宝流水号",
                               "aliases": ["支付宝流水号", "流水号"]},
            "processed_at": {"type": "date", "required": False, "desc": "处理日期",
                             "aliases": ["售后处理日期", "处理日期", "日期"]},
            "status": {"type": "str", "required": False, "desc": "售后状态",
                       "aliases": ["售后状态", "状态"]},
            "remark": {"type": "str", "required": False, "desc": "备注",
                       "aliases": ["备注"]},
        },
        "group_by": [], "parent_fields": [],
    },
    "delivery_note": {
        "label": "供应商送货单",
        "description": "每行是一行明细; 同一 supplier_name + note_no 的行合并为一张送货单。",
        "fields": {
            "supplier_name": {
                "type": "str", "required": True,
                "desc": "供应商名称 (没注册过会自动创建)",
                "aliases": ["供应商", "厂家", "工厂", "供货商", "Supplier"],
            },
            "note_no": {
                "type": "str", "required": False,
                "desc": "送货单号",
                "aliases": ["单号", "送货单号", "单据号", "票号", "NoteNo", "DN号"],
            },
            "delivery_date": {
                "type": "date", "required": True,
                "desc": "送货/到货日期",
                "aliases": ["日期", "送货日期", "到货日期", "下单日期", "出库日期", "Date"],
            },
            "item_name": {
                "type": "str", "required": True,
                "desc": "品名/商品名",
                "aliases": ["品名", "商品", "商品名", "货品", "名称", "Item"],
            },
            "spec": {
                "type": "str", "required": False,
                "desc": "规格尺寸 (如 1800×850)",
                "aliases": ["规格", "尺寸", "型号", "Spec", "Size"],
            },
            "unit": {
                "type": "str", "required": False,
                "desc": "单位 (件/张/块/片/套)",
                "aliases": ["单位", "Unit"],
            },
            "qty": {
                "type": "decimal", "required": True,
                "desc": "数量",
                "aliases": ["数量", "件数", "Qty", "Quantity"],
            },
            "unit_price": {
                "type": "decimal", "required": False,
                "desc": "单价 (元)",
                "aliases": ["单价", "单价(元)", "Price", "UnitPrice"],
            },
            "amount": {
                "type": "decimal", "required": False,
                "desc": "金额 (元, 缺省会用 单价×数量 自动填)",
                "aliases": ["金额", "合计", "小计", "总额", "Amount", "Total"],
            },
            "total_amount": {
                "type": "decimal", "required": False,
                "desc": "整张单总金额 (如果 Excel 单独列了一张单的合计, 写这里)",
                "aliases": ["单据合计", "票面金额", "总计"],
            },
            "status": {
                "type": "str", "required": False,
                "desc": "状态: pending_review/confirmed/billed/paid/disputed",
                "aliases": ["状态", "对账状态", "付款状态"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "说明", "Note", "Remark"],
            },
        },
        "group_by": ["supplier_name", "note_no"],
        "parent_fields": ["supplier_name", "note_no", "delivery_date",
                          "total_amount", "status", "remark"],
    },
    "alipay_flow": {
        "label": "支付宝流水",
        "description": "导入支付宝导出的 Excel/CSV (任意列结构)。一行 = 一条 AlipayFlow。",
        "fields": {
            "account": {
                "type": "str", "required": True,
                "desc": "支付宝账户 (企业号 / 个体户私账 / 爱群号 / 佳宝号 / 主力号)",
                "aliases": ["账户", "账号", "支付宝账号", "Account"],
            },
            "transaction_no": {
                "type": "str", "required": True,
                "desc": "交易流水号 (同一账户内全局唯一)",
                "aliases": ["流水号", "交易号", "订单号", "TransactionNo"],
            },
            "transaction_time": {
                "type": "datetime", "required": False,
                "desc": "交易时间",
                "aliases": ["时间", "交易时间", "Time"],
            },
            "transaction_type": {
                "type": "str", "required": False,
                "desc": "交易类型 (在线支付 / 转账 / 分账 / ...)",
                "aliases": ["交易类型", "类型", "Type"],
            },
            "counterparty": {
                "type": "str", "required": False,
                "desc": "对手方姓名/公司",
                "aliases": ["交易对象", "交易对方", "对方", "对手方", "对方姓名", "收款方"],
            },
            "counterparty_account": {
                "type": "str", "required": False,
                "desc": "对手方账号",
                "aliases": ["交易账户", "对方账号", "收款账号"],
            },
            "amount": {
                "type": "decimal", "required": True,
                "desc": "金额 (正=收入, 负=支出; 如果 Excel 是 收入/支出 分开两列, 请只选其一并加负号)",
                "aliases": ["金额", "Amount"],
            },
            "balance": {
                "type": "decimal", "required": False,
                "desc": "交易后余额",
                "aliases": ["余额", "账户余额", "Balance"],
            },
            "related_order_no": {
                "type": "str", "required": False,
                "desc": "关联的平台订单号",
                "aliases": ["商户订单号", "订单号", "OrderNo"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "摘要", "Note"],
            },
        },
        "group_by": ["account", "transaction_no"],
        "parent_fields": list(),
    },
    "factory_order": {
        "label": "工厂下单",
        "description": "每行 = 一张工厂订单 (FactoryOrder)。",
        "fields": {
            "factory_order_no": {
                "type": "str", "required": True,
                "desc": "工厂订单号",
                "aliases": ["工厂订单号", "下单号", "厂单号"],
            },
            "platform_order_no": {
                "type": "str", "required": False,
                "desc": "对应的平台订单号 (淘宝/抖音)",
                "aliases": ["关联平台订单号", "平台订单号", "淘宝单号", "订单号"],
            },
            "factory_name": {
                "type": "str", "required": False,
                "desc": "工厂名",
                "aliases": ["工厂名称", "工厂", "厂家", "供应商"],
            },
            "order_date": {
                "type": "date", "required": False,
                "desc": "下单日期",
                "aliases": ["下单日期", "日期"],
            },
            "expected_delivery": {
                "type": "date", "required": False,
                "desc": "预计交付日期",
                "aliases": ["预计交付", "交期", "预计到货"],
            },
            "actual_delivery": {
                "type": "date", "required": False,
                "desc": "实际交付日期",
                "aliases": ["实际交付", "实际到货", "到货日期"],
            },
            "product_code": {
                "type": "str", "required": False,
                "desc": "产品编码",
                "aliases": ["产品编码", "货号", "型号"],
            },
            "sku": {
                "type": "str", "required": False,
                "desc": "SKU/规格描述",
                "aliases": ["SKU", "规格", "款式"],
            },
            "qty": {
                "type": "int", "required": False,
                "desc": "数量",
                "aliases": ["数量", "件数"],
            },
            "unit_price": {
                "type": "decimal", "required": False,
                "desc": "单价",
                "aliases": ["单价", "Price"],
            },
            "factory_bill_amount": {
                "type": "decimal", "required": False,
                "desc": "工厂账单金额",
                "aliases": ["工厂账单", "账单金额", "金额"],
            },
            "payment_method": {
                "type": "str", "required": False,
                "desc": "付款方式 (月结/现付/预付)",
                "aliases": ["付款方式", "结算"],
            },
            "payment_status": {
                "type": "str", "required": False,
                "desc": "付款状态",
                "aliases": ["付款状态", "对账"],
            },
            "remark": {
                "type": "str", "required": False,
                "desc": "备注",
                "aliases": ["备注", "说明"],
            },
        },
        "group_by": ["factory_order_no"],
        "parent_fields": list(),  # factory_order 整体是一行, 无父子
    },
}


def get_schema(entity_type: str) -> EntitySchema:
    if entity_type not in ENTITY_SCHEMAS:
        raise ValueError(f"未知实体类型: {entity_type}. 支持: {list(ENTITY_SCHEMAS)}")
    return ENTITY_SCHEMAS[entity_type]


def list_entity_types() -> list[dict]:
    return [
        {"value": k, "label": v["label"], "description": v["description"]}
        for k, v in ENTITY_SCHEMAS.items()
    ]
